import type {CombatEvent} from './combat.ts';
type AudioMode='menu'|'fight'|'boss'|'victory';
export class ArcadeAudio {
 context:AudioContext|null=null;musicGain:GainNode|null=null;fxGain:GainNode|null=null;music=.38;effects=.7;mode:AudioMode='menu';timer:ReturnType<typeof setInterval>|null=null;next=0;beat=0;paused=false;
 async unlock(){if(!this.context){this.context=new AudioContext();this.musicGain=this.context.createGain();this.fxGain=this.context.createGain();const compressor=this.context.createDynamicsCompressor();compressor.threshold.value=-12;compressor.ratio.value=8;this.musicGain.connect(compressor);this.fxGain.connect(compressor);compressor.connect(this.context.destination);this.apply();}await this.context.resume();if(!this.timer){this.next=this.context.currentTime+.08;this.timer=setInterval(()=>this.schedule(),30);}}
 apply(){if(this.context){this.musicGain!.gain.setTargetAtTime(this.paused?0:this.music*.35,this.context.currentTime,.06);this.fxGain!.gain.setTargetAtTime(this.effects*.6,this.context.currentTime,.03);}}
 volumes(music:number,effects:number){this.music=music;this.effects=effects;this.apply();}
 setMode(mode:AudioMode){if(this.mode!==mode){this.mode=mode;this.beat=0;this.next=(this.context?.currentTime??0)+.08;}}
 pause(paused:boolean){this.paused=paused;this.apply();}
 tone(freq:number,time:number,duration:number,type:OscillatorType,volume:number,target?:number,music=false){const c=this.context;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(20,freq),time);if(target)o.frequency.exponentialRampToValueAtTime(Math.max(20,target),time+duration);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(Math.max(.0002,volume),time+.006);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g);g.connect(music?this.musicGain!:this.fxGain!);o.start(time);o.stop(time+duration+.02);}
 noise(time:number,duration:number,volume:number,highpass=800,music=false){const c=this.context;if(!c)return;const buffer=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),data=buffer.getChannelData(0);let seed=813;for(let i=0;i<data.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=(seed/4294967296*2-1)*(1-i/data.length);}const source=c.createBufferSource(),g=c.createGain(),filter=c.createBiquadFilter();source.buffer=buffer;filter.type='highpass';filter.frequency.value=highpass;g.gain.value=volume;source.connect(filter);filter.connect(g);g.connect(music?this.musicGain!:this.fxGain!);source.start(time);}
 schedule(){const c=this.context;if(!c||c.state!=='running')return;if(this.next<c.currentTime-.2)this.next=c.currentTime+.02;let count=0;while(this.next<c.currentTime+.14&&count++<8){const b=this.beat%128,tempo=this.mode==='boss'?146:this.mode==='menu'?112:132,step=60/tempo/4;const root=[48,53,55,51][Math.floor(b/32)];const scale=this.mode==='boss'?[0,3,6,7,10,12,15,19]:[0,4,7,9,12,16,14,7];const melody=[0,2,4,2,5,4,3,2,1,3,5,3,6,5,2,4];const midi=(note:number)=>440*2**((note-69)/12);if(!this.paused){if(b%2===0)this.tone(midi(root+12+scale[melody[Math.floor(b/2)%16]]),this.next,step*1.8,'square',.11,undefined,true);if(b%4===0)this.tone(midi(root+(b%8===0?0:7)),this.next,step*3.3,'triangle',.4,undefined,true);if(b%16===0||b%16===10)this.tone(150,this.next,.13,'sine',.48,35,true);if(b%16===4||b%16===12){this.noise(this.next,.11,.16,1200,true);this.tone(185,this.next,.07,'triangle',.18,70,true);}if(b%2===1)this.noise(this.next,.026,.065,6500,true);if(b%8===2)this.tone(midi(root+scale[b%3]+24),this.next,step*.7,'triangle',.1,undefined,true);}this.beat++;this.next+=step;}}
 sound(type:CombatEvent['type']|'menu'|'select'){const c=this.context;if(!c)return;const t=c.currentTime+.005;switch(type){case'menu':this.tone(550,t,.06,'square',.11,740);break;case'select':this.tone(660,t,.08,'square',.15);this.tone(990,t+.08,.15,'triangle',.22);break;case'punch':this.noise(t,.055,.16,1800);this.tone(145,t,.06,'triangle',.14,70);break;case'kick':this.noise(t,.11,.22,650);this.tone(210,t,.09,'sawtooth',.11,50);break;case'hit':this.noise(t,.13,.4,420);this.tone(130,t,.14,'square',.2,36);break;case'block':this.tone(420,t,.11,'square',.15,170);this.noise(t,.06,.2,3600);break;case'jump':this.tone(200,t,.12,'square',.11,650);break;case'special':this.tone(150,t,.22,'sawtooth',.13,980);this.tone(800,t+.16,.3,'triangle',.25,200);this.noise(t+.12,.25,.13,2400);break;case'parry':[880,1760,1320].forEach((f,i)=>this.tone(f,t+i*.04,.13,'triangle',.3));break;case'tag':this.tone(330,t,.12,'square',.18,880);this.tone(990,t+.1,.16,'triangle',.2);break;case'ultra':[130,260,520,1040].forEach((f,i)=>this.tone(f,t+i*.055,.32,'sawtooth',.1));this.noise(t+.2,.35,.25,600);break;case'ko':this.tone(340,t,.5,'sawtooth',.15,40);break;case'round':[440,660,880].forEach((f,i)=>this.tone(f,t+i*.1,.2,'square',.13));break;case'win':[523,659,784,1046,784,1046].forEach((f,i)=>this.tone(f,t+i*.15,.25,'square',.16));break;}}
 destroy(){if(this.timer)clearInterval(this.timer);this.timer=null;void this.context?.close();}
}
