import type {CombatEvent} from './combat.ts';
import {SnesMusic} from './snes-music.ts';
import {areaScore} from './area-music.ts';
import {midiScore,originalScore,type MusicScore,type MusicMode as AudioMode} from './music-score.ts';
export class ArcadeAudio {
 context:AudioContext|null=null;musicGain:GainNode|null=null;fxGain:GainNode|null=null;music=.38;effects=.7;mode:AudioMode='menu';timer:ReturnType<typeof setInterval>|null=null;paused=false;private soundtrack:SnesMusic|null=null;private arrangements=new Map<AudioMode,MusicScore>();
 async unlock(){if(!this.context){this.context=new AudioContext();this.musicGain=this.context.createGain();this.fxGain=this.context.createGain();const compressor=this.context.createDynamicsCompressor();compressor.threshold.value=-12;compressor.ratio.value=8;this.musicGain.connect(compressor);this.fxGain.connect(compressor);compressor.connect(this.context.destination);this.soundtrack=new SnesMusic(this.context,this.musicGain);this.soundtrack.setScore(this.currentScore());this.soundtrack.pause(this.paused);this.apply();}await this.context.resume();if(!this.timer){this.timer=setInterval(()=>this.schedule(),30);}}
 apply(){if(this.context){this.musicGain!.gain.setTargetAtTime(this.paused?0:this.music*.35,this.context.currentTime,.06);this.fxGain!.gain.setTargetAtTime(this.effects*.6,this.context.currentTime,.03);}}
 volumes(music:number,effects:number){this.music=music;this.effects=effects;this.apply();}
 setMode(mode:AudioMode){if(this.mode!==mode){this.mode=mode;this.soundtrack?.setScore(this.currentScore());}}
 private arenaId:string|null=null;private previewId:string|null=null;
 private currentScore(){return this.previewId==='@title'?(this.arrangements.get('menu')??originalScore('menu')):this.previewId?areaScore(this.previewId):this.arrangements.get(this.mode)??this.defaultScore()}
 previewArea(id:string|null){if(id)areaScore(id);this.previewId=id;this.soundtrack?.setScore(this.currentScore());}
 previewTitle(){this.previewId='@title';this.soundtrack?.setScore(this.currentScore())}
 get hasTitleMidi(){return this.arrangements.has('menu')}
 private defaultScore(){return this.arenaId&&(this.mode==='fight'||this.mode==='boss')?areaScore(this.arenaId):originalScore(this.mode)}
 setArena(id:string,boss=false){areaScore(id);const mode=boss?'boss':'fight';if(this.arenaId===id&&this.mode===mode)return;this.arenaId=id;this.mode=mode;this.soundtrack?.setScore(this.currentScore());}
 useMidi(mode:AudioMode,bytes:ArrayBuffer|Uint8Array,title:string){const score=midiScore(bytes,title);this.arrangements.set(mode,score);if(this.mode===mode)this.soundtrack?.setScore(this.currentScore());}
 get trackTitle(){return this.currentScore().title}
 pause(paused:boolean){this.paused=paused;this.soundtrack?.pause(paused);this.apply();}
 tone(freq:number,time:number,duration:number,type:OscillatorType,volume:number,target?:number,music=false){const c=this.context;if(!c)return;const o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(Math.max(20,freq),time);if(target)o.frequency.exponentialRampToValueAtTime(Math.max(20,target),time+duration);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(Math.max(.0002,volume),time+.006);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g);g.connect(music?this.musicGain!:this.fxGain!);o.start(time);o.stop(time+duration+.02);}
 noise(time:number,duration:number,volume:number,highpass=800,music=false){const c=this.context;if(!c)return;const buffer=c.createBuffer(1,Math.ceil(c.sampleRate*duration),c.sampleRate),data=buffer.getChannelData(0);let seed=813;for(let i=0;i<data.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=(seed/4294967296*2-1)*(1-i/data.length);}const source=c.createBufferSource(),g=c.createGain(),filter=c.createBiquadFilter();source.buffer=buffer;filter.type='highpass';filter.frequency.value=highpass;g.gain.value=volume;source.connect(filter);filter.connect(g);g.connect(music?this.musicGain!:this.fxGain!);source.start(time);}
 schedule(){this.soundtrack?.schedule();}
 sound(type:CombatEvent['type']|'menu'|'select'){const c=this.context;if(!c)return;const t=c.currentTime+.005;switch(type){case'menu':this.tone(550,t,.06,'square',.11,740);break;case'select':this.tone(660,t,.08,'square',.15);this.tone(990,t+.08,.15,'triangle',.22);break;case'punch':this.noise(t,.055,.16,1800);this.tone(145,t,.06,'triangle',.14,70);break;case'kick':this.noise(t,.11,.22,650);this.tone(210,t,.09,'sawtooth',.11,50);break;case'hit':this.noise(t,.13,.4,420);this.tone(130,t,.14,'square',.2,36);break;case'block':this.tone(420,t,.11,'square',.15,170);this.noise(t,.06,.2,3600);break;case'jump':this.tone(200,t,.12,'square',.11,650);break;case'special':this.tone(150,t,.22,'sawtooth',.13,980);this.tone(800,t+.16,.3,'triangle',.25,200);this.noise(t+.12,.25,.13,2400);break;case'parry':[880,1760,1320].forEach((f,i)=>this.tone(f,t+i*.04,.13,'triangle',.3));break;case'tag':this.tone(330,t,.12,'square',.18,880);this.tone(990,t+.1,.16,'triangle',.2);break;case'ultra':[130,260,520,1040].forEach((f,i)=>this.tone(f,t+i*.055,.32,'sawtooth',.1));this.noise(t+.2,.35,.25,600);break;case'ko':this.tone(340,t,.5,'sawtooth',.15,40);break;case'round':[440,660,880].forEach((f,i)=>this.tone(f,t+i*.1,.2,'square',.13));break;case'win':[523,659,784,1046,784,1046].forEach((f,i)=>this.tone(f,t+i*.15,.25,'square',.16));break;}}
 destroy(){if(this.timer)clearInterval(this.timer);this.timer=null;this.soundtrack?.destroy();this.soundtrack=null;void this.context?.close();}
}
