'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {fighter,station} from './data';
import {createMatch,activeMove,type Match,type Input} from './combat';
import {SPECIAL_STAGES} from './stages';
import {useMenuPad} from './useMenuPad';
import {MoveList} from './MoveList';
import {TourMap} from './TourMap';
import {FighterPortrait} from './FighterPortrait';
import type {ArcadeAudio} from './audio';
import type {BattleConfig,BattleHandle} from './scene';
export function battleOptions(config:BattleConfig){return {stageId:config.stationId,parry:config.parry,turbo:config.turbo,partners:config.partners}}
function Hud({match}:{match:Match}){return <><div className="hud">{[0,1,2].map(slot=>slot===1?<div className="timer" key="timer">{Math.ceil(match.time/60).toString().padStart(2,'0')}<small>RUNDE {match.round}</small></div>:<div key={slot} className={`fighter-hud ${slot===2?'right':''}`}>{(()=>{const i=slot===2?1:0,a=match.actors[i],d=fighter(a.id),bench=match.bench[i];return <><div className="hud-name"><span>{d.name}</span><span className="small">{i+1}P</span></div><div className="life-track" role="meter" aria-label={`${d.name} Lebensenergie`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={a.hp}><div className="life-fill" style={{width:`${a.hp}%`}}/></div><div className="round-gems">{'◆'.repeat(match.score[i])}{'◇'.repeat(2-match.score[i])}</div>{bench&&<div className={`reserve ${bench.hp===0?'out':''}`}><FighterPortrait id={bench.id}/><span>{fighter(bench.id).short}<i><b style={{width:bench.hp+'%'}}/></i><small>{bench.hp===0?'K.O.':match.tagCd[i]>0?'WECHSEL '+Math.ceil(match.tagCd[i]/60):'WECHSEL BEREIT'}</small></span></div>}</>})()}</div>)}</div><div className="super-hud">{match.actors.map((a,i)=><div key={i} className={`super-panel ${match.meter[i]>=100?'charged':''}`}><strong>{match.meter[i]>=100?'ULTRA BEREIT':'SUPER'} <span>{Math.floor(match.meter[i])}%</span></strong><div role="meter" aria-label={`Spieler ${i+1} Super`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={match.meter[i]}><i style={{width:match.meter[i]+'%'}}/></div><small>{a.specialCd===0?'SPECIAL BEREIT':'SPECIAL '+Math.ceil(a.specialCd/60)+'s'} · {i?'O':'R'} ULTRA {match.rules.parry?`· ${i?'I':'Q'} PARRY`:''}</small><span className="sr-only">{activeMove(a).name}</span></div>)}</div></>}
export function BattleView({config,audio,onDone,onBack,tour}:{config:BattleConfig;audio:ArcadeAudio;tour?:{route:string[];index:number};onDone:(winner:number)=>void;onBack:()=>void}){const host=useRef<HTMLDivElement>(null),handle=useRef<BattleHandle|null>(null);const [match,setMatch]=useState(()=>createMatch(config.p1,config.p2,19,battleOptions(config))),[paused,setPaused]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[showMap,setShowMap]=useState(false);
 useEffect(()=>{let active=true;void import('./scene').then(({mountBattle})=>{if(!active||!host.current)return;handle.current=mountBattle(host.current,config,audio,m=>{setLoading(false);setMatch({...m,actors:m.actors.map(a=>({...a})) as Match['actors'],bench:m.bench.map(a=>a?{...a}:null) as Match['bench'],meter:[...m.meter],score:[...m.score],tagCd:[...m.tagCd]})},onDone,()=>setPaused(true));}).catch(()=>setError('Die Arena konnte nicht geladen werden. Bitte lade das Spiel neu.'));return()=>{active=false;handle.current?.destroy();audio.pause(false)}},[]);
 const pause=(value:boolean)=>{setPaused(value);handle.current?.pause(value)};
 useMenuPad(paused,()=>pause(false));
 const touch=(name:keyof Input,label:string)=><button key={name} aria-label={label} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);handle.current?.touch(name,true)}} onPointerUp={()=>handle.current?.touch(name,false)} onPointerCancel={()=>handle.current?.touch(name,false)}>{label}</button>;
 const note=SPECIAL_STAGES.find(s=>s.id===config.stationId)?.note;
 return <><div className="fight-topline"><span className="arena-title">{station(config.stationId).name.toUpperCase()}</span><div className="fight-menu-buttons">{tour&&<button className="text-button" onClick={()=>{setShowMap(true);pause(true)}}>▦ Parkplan</button>}<button className="text-button" onClick={()=>{setShowMap(false);pause(true)}}>Ⅱ Pause / Moves · Esc</button></div></div><div className="fight-shell scanlines"><div className="battle-stage"><div className="phaser-host" ref={host}/>{loading&&!error&&<div className="battle-loading">DIE ARENA ÖFFNET …</div>}{error&&<div className="error-state"><p>{error}</p><button onClick={onBack}>Zum Menü</button></div>}<Hud match={match}/>{note&&<p className="stage-rule">{note}</p>}</div></div><div className="touch-controls"><div className="touch-group">{touch('left','←')}{touch('down','↓')}{touch('right','→')}{touch('jump','↑')}</div><div className="touch-group">{touch('punch','Faust')}{touch('kick','Kick')}{touch('block','Block')}{config.parry&&touch('parry','Parry')}{touch('ultra','Ultra')}{config.partners?.[0]&&touch('tag','Tag')}</div></div><Dialog open={paused} onOpenChange={pause}><DialogContent container={typeof document==='undefined'?null:document.getElementById('game-screen')} className={`game-dialog ${showMap?'map-dialog':'moves-dialog'}`}><DialogTitle>{showMap?'DEIN STANDORT':'PAUSE · MOVE LIST'}</DialogTitle><DialogDescription>{showMap?'Die Arena pausiert, während du die Karte ansiehst.':'Vorwärts zeigt immer zum Gegner. Charge: zurück halten, dann vorwärts + Faust.'}</DialogDescription>{tour&&showMap?<TourMap route={tour.route} index={tour.index} compact/>:<><div className="move-columns">{match.actors.map((a,i)=><MoveList key={i} id={a.id} player={i}/>)}</div><p>Block: H / L · Parry: Q / I {config.parry?'(aktiv)':'(aus)'} · Teamwechsel: E / P · Gamepad: LB Block, RB Parry, Y Ultra, LT Wechsel.</p></>}<div className="pause-actions">{tour&&!showMap&&<button className="arcade-button secondary" onClick={()=>setShowMap(true)}>Parkplan ansehen</button>}<button className="arcade-button" onClick={()=>pause(false)}>Weiterspielen →</button><button className="arcade-button secondary" onClick={onBack}>Zurück zum Menü</button></div></DialogContent></Dialog></>;
}
