import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,neutral,step,comboReady,createBrain,aiInput,type Input,type Match} from './combat.ts';
import {FIGHTERS,HEROES,STATIONS,SHORT_TOUR,FULL_TOUR,type FighterId} from './data.ts';
import {padInput} from './input.ts';
const ready=(a:FighterId='ed',b:FighterId='snorri')=>{const m=createMatch(a,b);for(let i=0;i<150;i++)step(m,[neutral(),neutral()]);assert.equal(m.phase,'fight');return m;};
function ticks(m:Match,n:number,a=neutral(),b=neutral()){for(let i=0;i<n;i++)step(m,[a,b]);}
function combo(m:Match,p=0){const a=neutral();a.down=true;const b=neutral();b[m.actors[p].face===1?'right':'left']=true;const c=neutral();c.punch=true;for(const input of [a,neutral(),b,neutral(),c])step(m,p===0?[input,neutral()]:[neutral(),input]);}
test('roster includes Wakala and the playable tour contains only 21 themed areas',()=>{assert.equal(HEROES.length,41);assert.equal(new Set(HEROES.map(f=>f.id)).size,HEROES.length);for(const id of ['karsten','edda','scholz','wakala'])assert.ok(HEROES.some(f=>f.id===id));assert.equal(STATIONS.filter(s=>s.kind==='Themenbereich').length,21);assert.equal(STATIONS.filter(s=>s.kind==='Achterbahn').length,0);assert.equal(STATIONS.length,21);assert.equal(new Set(FULL_TOUR).size,21);assert.equal(SHORT_TOUR.length,8);assert.ok(FULL_TOUR.every(id=>STATIONS.some(s=>s.id===id)));assert.ok(SHORT_TOUR.every(id=>STATIONS.some(s=>s.id===id)));for(const f of FIGHTERS){assert.ok(f.special);assert.ok(f.cooldown>0)}});
test('all character specials activate in either facing direction and produce damage',()=>{for(const f of FIGHTERS){for(const reverse of [false,true]){const m=ready(f.id,'ed');m.actors[0].x=reverse?560:400;m.actors[1].x=reverse?400:560;step(m,[neutral(),neutral()]);combo(m);assert.equal(m.actors[0].action,'special',f.id+' combo');assert.ok(m.actors[0].specialCd>0);ticks(m,110);assert.ok(m.actors[1].hp<100,`${f.id} special must hit (${reverse})`);}}});
test('combo expires, respects order and consumes only once',()=>{assert.equal(comboReady([{key:'down',tick:1},{key:'forward',tick:3},{key:'punch',tick:5}],5),true);assert.equal(comboReady([{key:'down',tick:1},{key:'forward',tick:3},{key:'punch',tick:65}],65),false);assert.equal(comboReady([{key:'forward',tick:1},{key:'down',tick:3},{key:'punch',tick:5}],5),false);const m=ready();combo(m);const cd=m.actors[0].specialCd;ticks(m,60);combo(m);assert.notEqual(m.actors[0].action,'special');assert.ok(m.actors[0].specialCd<cd)});
test('punch hits once; holding punch does not auto-repeat; out of range misses',()=>{const m=ready();m.actors[1].x=340;const attack={...neutral(),punch:true};ticks(m,100,attack);assert.equal(m.actors[1].hp,92);const far=ready();ticks(far,50,attack);assert.equal(far.actors[1].hp,100)});
test('block reduces damage and its recovery ends',()=>{const m=ready();m.actors[1].x=340;ticks(m,60,{...neutral(),punch:true},{...neutral(),block:true});assert.equal(m.actors[1].hp,99);ticks(m,30);assert.equal(m.actors[1].action,'idle')});
test('jump lands, fighters stay in bounds, and a jump clears a wave',()=>{const m=ready('snorri','ed');ticks(m,50,{...neutral(),left:true,jump:true});assert.equal(m.actors[0].y,0);assert.ok(m.actors[0].x>=65);m.actors[0].x=350;m.actors[1].x=600;combo(m);ticks(m,35);ticks(m,1,neutral(),{...neutral(),jump:true});ticks(m,40);assert.equal(m.actors[1].hp,100)});
test('boss telegraph precedes its wave by 44 simulation frames',()=>{const m=ready('graumacher','ed');combo(m);ticks(m,40);assert.equal(m.projectiles.length,0);ticks(m,4);assert.equal(m.projectiles.length,1)});
test('time-out, tied rounds, two round wins, defeat and completion',()=>{const tie=ready();tie.time=1;step(tie,[neutral(),neutral()]);assert.equal(tie.roundWinner,null);ticks(tie,145);assert.equal(tie.round,2);const m=ready();for(let r=0;r<2;r++){m.actors[1].hp=0;step(m,[neutral(),neutral()]);assert.equal(m.phase,'roundover');assert.equal(m.actors[0].action,'victory');assert.equal(m.actors[1].action,'defeat');ticks(m,145);if(r===0)ticks(m,110);}assert.equal(m.phase,'complete');assert.equal(m.winner,0);assert.equal(m.actors[0].wins,2)});
test('deterministic fixed-tick AI duel reaches a result with finite positions',()=>{const run=()=>{const m=ready('michael','graumacher'),a=createBrain(),b=createBrain();for(let i=0;i<30000&&m.phase!=='complete';i++){step(m,[aiInput(m,0,.8,a),aiInput(m,1,.6,b)]);for(const p of m.actors){assert.ok(Number.isFinite(p.x)&&Number.isFinite(p.y));assert.ok(p.hp>=0&&p.hp<=100)}}assert.equal(m.phase,'complete');return {winner:m.winner,hp:m.actors.map(a=>a.hp),tick:m.tick}};assert.deepEqual(run(),run())});
test('complete long tour visits 21 themed arenas and resolves its final boss through actual AI fights',()=>{let resolved=0;for(let i=0;i<FULL_TOUR.length;i++){const m=ready(HEROES[i%HEROES.length].id,i===FULL_TOUR.length-1?'graumacher':HEROES[(i+3)%HEROES.length].id),a=createBrain(),b=createBrain();for(let n=0;n<30000&&m.phase!=='complete';n++)step(m,[aiInput(m,0,.85,a),aiInput(m,1,.2+i*.02,b)]);assert.equal(m.phase,'complete',FULL_TOUR[i]);resolved++;}assert.equal(resolved,21)});
test('standard gamepad maps both movement and the three sequential special inputs',()=>{const pad={connected:true,axes:[0,0],buttons:Array.from({length:16},()=>({pressed:false}))};assert.deepEqual(padInput(pad as unknown as Gamepad),neutral());pad.buttons[13].pressed=true;assert.equal(padInput(pad as unknown as Gamepad).down,true);pad.buttons[13].pressed=false;pad.axes[0]=1;assert.equal(padInput(pad as unknown as Gamepad).right,true);pad.axes[0]=0;pad.buttons[2].pressed=true;assert.equal(padInput(pad as unknown as Gamepad).punch,true);assert.equal(padInput(null).punch,false)});
