'use client';
import {useEffect,useRef,useState} from 'react';
import {ENDINGS} from './endings';
import {fighter,type FighterId} from './data';
import {arenaImage} from './arena-art';
import type {Costume} from './rules';
import {loadCostumeSheet} from './costume-art';
export function EndingScreen({hero,costume='classic',onDone}:{hero:FighterId;costume?:Costume;onDone:()=>void}){const data=ENDINGS[hero==='graumacher'?'ed':hero],canvas=useRef<HTMLCanvasElement>(null),[chapter,setChapter]=useState(0),[caption,setCaption]=useState(''),[ready,setReady]=useState(false);const done=useRef(onDone);done.current=onDone;const skip=useRef(()=>{});
 useEffect(()=>{let alive=true,raf=0,time=0,last=0,loaded=false,chapterIndex=-1,letters=-1,padHeld=true;const ctx=canvas.current!.getContext('2d')!,backgrounds=data.stages.map(id=>{const img=new Image();img.src=arenaImage(id);return img}),walk=new Image(),guest=new Image();walk.src=`/assets/walk/${hero}.png`;guest.src=`/assets/${data.guest}.png`;let heroSheet:CanvasImageSource|null=null,heroAction:CanvasImageSource|null=null;void loadCostumeSheet(hero,costume).then(sheet=>{heroAction=sheet}).catch(()=>{});void loadCostumeSheet(hero,costume,'walk').then(sheet=>{heroSheet=sheet}).catch(()=>{});const action=new Image();action.src=`/assets/${hero}.png`;const load=(img:HTMLImageElement)=>new Promise<void>(r=>{if(img.complete&&img.naturalWidth)r();else{img.onload=()=>r();img.onerror=()=>r()}});void Promise.all([...backgrounds,walk,guest,action].map(load)).then(()=>{loaded=true;if(alive)setReady(true)});const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const advance=()=>{if(!loaded)return;time=(Math.floor(time/5)+1)*5;if(time>=15)done.current()};skip.current=advance;
 const key=(e:KeyboardEvent)=>{if(e.repeat)return;if(['Enter','Space','Escape'].includes(e.code)){e.preventDefault();e.stopPropagation();if(e.code==='Escape')done.current();else advance()}};window.addEventListener('keydown',key);
 const draw=(now:number)=>{if(!alive)return;raf=requestAnimationFrame(draw);const dt=last?Math.min((now-last)/1000,.05):0;last=now;if(!loaded)return;if(!document.hidden)time+=dt;if(time>=15){alive=false;done.current();return}const n=Math.min(2,Math.floor(time/5)),phase=time%5;if(n!==chapterIndex){chapterIndex=n;setChapter(n);letters=-1}const count=reduced?data.lines[n].length:Math.min(data.lines[n].length,Math.floor(phase*38));if(letters!==count){letters=count;setCaption(data.lines[n].slice(0,count))}ctx.imageSmoothingEnabled=false;ctx.fillStyle='#09152e';ctx.fillRect(0,0,640,360);const bg=backgrounds[n],pan=reduced?0:phase*2;if(bg.naturalWidth)ctx.drawImage(bg,-pan,-10,660,371);ctx.fillStyle='#0d193833';ctx.fillRect(0,0,640,360);
 const x=n===0?Math.min(298,100+phase*43):n===1?330:285,frame=reduced?0:Math.floor(phase*5)%4;
 if(n===0&&walk.naturalWidth)ctx.drawImage(heroSheet??walk,frame*256,0,256,256,x-95,83,190,190);else if(action.naturalWidth)ctx.drawImage(heroAction??action,3*256,3*256,256,256,x-95,83+(reduced?0:Math.sin(phase*3)*2),190,190);
 if(n===2&&guest.naturalWidth){ctx.save();ctx.translate(470,0);ctx.scale(-1,1);ctx.drawImage(guest,768,768,256,256,0,96,178,178);ctx.restore()}
 if(!reduced&&n>0)for(let j=0;j<22;j++){const px=(j*97+phase*24)%640,py=30+(j*43+phase*19)%205;ctx.fillStyle=['#ffe294','#92eafa','#ed91ce'][j%3];ctx.fillRect(px|0,py|0,2,2)}
 if(phase<.25&&!reduced){ctx.fillStyle=`rgba(4,10,25,${1-phase/.25})`;ctx.fillRect(0,0,640,360)}const pad=Array.from(navigator.getGamepads?.()??[]).find(Boolean),pressed=!!pad?.buttons[0]?.pressed;if(pressed&&!padHeld)advance();padHeld=pressed;
 };raf=requestAnimationFrame(draw);return()=>{alive=false;cancelAnimationFrame(raf);window.removeEventListener('keydown',key)};
 },[hero,costume]);
 return <section className="ending-screen" aria-label={`Arcade-Ending für ${fighter(hero).name}`}><canvas ref={canvas} width={640} height={360} aria-hidden="true"/><div className="ending-top"><span>MACKMEDIA · ARCADE ENDING</span><h1>{data.title}</h1><small>{fighter(hero).name} · {chapter+1} / 3</small></div><div className="ending-caption"><p aria-live="polite">{ready?caption:'DIE GESCHICHTE GEHT WEITER …'}</p><div><button onClick={()=>skip.current()}>ENTER / A · WEITER</button><button onClick={()=>done.current()}>ESC · ZUM ERGEBNIS</button></div></div></section>
}
