import type {FighterId} from './data.ts';
export interface Ending {title:string;stages:[string,string,string];lines:[string,string,string];guest:FighterId}
export const ENDINGS:Record<Exclude<FighterId,'graumacher'>,Ending>={
 wakala:{title:'Ein Lächeln im Wunderland',stages:['park-5','park-10','park-9'],lines:['Zwischen den Bäumen folgt Wakala dem letzten violetten Funken.','Mit einem überraschenden Hasen-Haken öffnet sich der Weg zum Licht.','Am Festplatz verbeugt sich der seltsame Gast. Heute endet der Spuk mit Applaus.'],guest:'snorri'},
 ed:{title:'Ein Park voller Sterne',stages:['park-9','park-3','park-14'],lines:['Ed findet den letzten Farbstern zwischen den Pflastersteinen.','Sein Sternensprint trägt das Leuchten bis zur höchsten Schiene.','Auf dem Festplatz wird aus dem Abenteuer ein neuer Film. Ed hat schon eine Idee für Teil zwei.'],guest:'snorri'},
 snorri:{title:'Sechs Arme, tausend Farben',stages:['park-19','park-20','park-14'],lines:['Snorri fängt die verlorenen Farben in sechs schillernden Wasserblasen.','Ein Strudel bringt das Wasser und die Musik zurück nach Skandinavien.','Die erste Vorführung auf dem Festplatz endet mit einer kleinen Wasserfontäne. Alle klatschen.'],guest:'ed'},
 roland:{title:'Die nächste große Kurve',stages:['park-17','park-3','park-9'],lines:['Roland betrachtet die wieder leuchtenden Schienen.','Ein goldener Bogen verbindet im Abendlicht Vergangenheit und Zukunft.','Auf dem Storyboard auf dem Festplatz zeichnet sich bereits das nächste große Abenteuer ab.'],guest:'michael'},
 marianne:{title:'Das Herz des Parks',stages:['park-5','park-9','park-14'],lines:['Marianne sammelt die Herzfunken unter den Bäumen des Märchenwalds.','An jeder Ecke begrüßt ein neues Leuchten die heimkehrenden Gäste.','Das Publikum hält diesen Moment fest: Ein Park lebt von den Menschen, die ihn teilen.'],guest:'roland'},
 juergen:{title:'Alles im Takt',stages:['park-11','park-8','park-9'],lines:['Jürgen hört, wie die Maschinen wieder ihren Rhythmus finden.','Mit einem letzten Taktgeber-Impuls laufen die Turbinen synchron.','Auf dem Festplatz blinkt die letzte Render-Anzeige grün. Premiere!'],guest:'thomas'},
 mauritia:{title:'Kristalle im Abendlicht',stages:['park-18','park-4','park-9'],lines:['Mauritia entdeckt die verstreuten Kristalle in den Bergen.','Über den Dächern bricht sich ihr Licht in allen Farben.','Die Kristallbögen werden zum funkelnden Schlussbild der neuen MackMedia-Sequenz.'],guest:'marianne'},
 michael:{title:'Das nächste Portal',stages:['park-11','park-3','park-9'],lines:['Michael öffnet ein Pixelportal im Herzen der Arena.','Dahinter wartet ein ganzer Kosmos voller ungeschriebener Geschichten.','Zurück auf dem Festplatz erscheint auf dem Storyboard ein neues Portal. Die Reise geht weiter.'],guest:'ed'},
 thomas:{title:'Ein Fest für alle',stages:['park-20','park-9','park-14'],lines:['Thomas lässt den letzten Feuerwirbel hoch über der Arena verglühen.','Die Lichter der Plätze gehen an. Aus dem Turnier wird ein großes Fest.','MackMedia fängt die jubelnde Parknacht ein. Der Abspann ist noch lange nicht das Ende.'],guest:'juergen'},
 annkathrin:{title:'Licht verbindet',stages:['park-11','park-16','park-9'],lines:['Ann-Kathrin setzt die erste Lichtbrücke über das dunkle Wasser.','Ein leuchtender Weg verbindet die Arenen des Parks.','Auf dem Festplatz wächst aus den einzelnen Wegen ein gemeinsames Bild.'],guest:'frederik'},
 frederik:{title:'Gemeinsam schneller',stages:['park-1','park-8','park-9'],lines:['Frederik startet mit einem letzten Team-Boost.','Über den Schienen ziehen zwei Lichtspuren gemeinsam ihre Bahn.','Der Film auf dem Festplatz endet mit einem Handschlag. Der nächste Start gehört dem ganzen Team.'],guest:'annkathrin'},
 alexia:{title:'Ein Prisma für die Nacht',stages:['park-3','park-20','park-14'],lines:['Alexia hebt das letzte Prisma vor die Sterne.','Sein Puls taucht die Kugel und die Galaxie in leuchtendes Violett.','MackMedia projiziert die neue Sternennacht auf die Festwand.'],guest:'miriam'},
 miriam:{title:'Die Farbe des Wassers',stages:['park-11','park-4','park-9'],lines:['Miriam folgt dem türkisfarbenen Band durch Kroatien.','Die Adria-Welle erreicht den Hafen. Jedes Boot trägt einen neuen Farbfunkel.','Auf dem Festplatz wird daraus eine Geschichte, die wie Wasser alles miteinander verbindet.'],guest:'alexia'},
 katja:{title:'Eine letzte Pirouette',stages:['park-3','park-14','park-9'],lines:['Katja dreht sich durch den ersten Sternenregen.','Die Lichter spiegeln ihre Pirouette auf dem festlichen Platz.','Die Kamera auf dem Festplatz fängt den letzten Schritt ein. Das ganze Team verbeugt sich.'],guest:'nicolas'},
 nicolas:{title:'Der Klang der Farben',stages:['park-17','park-13','park-9'],lines:['Nicolas lässt einen Resonanzring über die Dächer ziehen.','Die Antwort kommt von allen Arenen: ein gemeinsamer heller Akkord.','Auf dem Festplatz wird aus dem Echo die Titelmelodie eines neuen Abenteuers.'],guest:'katja'},
 max:{title:'Der perfekte Schnitt',stages:['park-8','park-20','park-14'],lines:['Max sammelt die schnellsten Momente des Turniers.','Ein Schnitt-Sprint verbindet Turbinenfunken und die letzte Achterbahnkurve.','Auf dem Festplatz sitzt der Schnitt genau auf dem Beat. Max setzt seine Cap zurecht: Noch ein Take!'],guest:'matthias'},
 matthias:{title:'Alles im Fokus',stages:['park-1','park-9','park-14'],lines:['Matthias richtet den letzten Fokusblitz auf den Horizont.','Zum ersten Mal seit dem Turnier liegt der ganze Platz wieder im Licht.','Unter seiner Cap lächelt er. Auf dem Festplatz steht das perfekte Schlussbild auf dem Monitor.'],guest:'max'},
 laurent:{title:'Licht an',stages:['park-6','park-3','park-9'],lines:['Laurent zieht eine goldene Lichtkante durch den stillen Hafen.','Eine Laterne nach der anderen beginnt zu leuchten.','Auf dem Festplatz genügt ein letzter Handgriff. Das Premierenlicht geht an.'],guest:'nathalie'},
 reinhold:{title:'Der Park hat Bass',stages:['park-5','park-2','park-9'],lines:['Reinholds Bassdruck vertreibt den letzten grauen Nebel.','Die Plätze antworten mit Rhythmus und jubelnden Gästen.','Auf dem Festplatz sitzt die Mischung. Auch Roland wippt nach dem Finale mit.'],guest:'andreas'},
 nathalie:{title:'Ein Himmel voller Farbe',stages:['park-16','park-5','park-9'],lines:['Nathalie schickt den letzten Farbflug über das Wasser.','Die Funken setzen sich wie kleine Sterne in die Bäume.','Auf dem Festplatz entsteht daraus ein bunter Abspann. Jeder im Team bekommt seinen eigenen Stern.'],guest:'laurent'},
 andreas:{title:'Der letzte Frame',stages:['park-3','park-11','park-9'],lines:['Andreas jagt mit dem Render-Rush dem letzten verlorenen Frame nach.','Eine violette Spur führt ihn durch den Kosmos zurück zum Park.','Auf dem Festplatz springt der Fortschritt auf hundert Prozent. Der Film läuft. Das Abenteuer bleibt.'],guest:'reinhold'}
};
