'use client';
import {useEffect,useRef,useState} from 'react';
import {fighter,type FighterId} from './data';
import {FighterPortrait} from './FighterPortrait';
import {STATIC_EDITION} from './platform';
import {readLocalScores,saveLocalScore} from './local-highscores';
type Row={initials:string;hero:FighterId;score:number};
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
export function HighscoreScreen({hero,score,tour,runId,onDone}:{hero:FighterId;score:number;tour:string;runId:string;onDone:()=>void}){
 const [letters,setLetters]=useState('AAA'),[cursor,setCursor]=useState(0),[rows,setRows]=useState<Row[]>([]),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{if(STATIC_EDITION){setRows(readLocalScores(localStorage,tour));return}const r=await fetch('/api/highscores?tour='+encodeURIComponent(tour));if(!r.ok)throw new Error('Rangliste gerade nicht erreichbar.');setRows(await r.json())};
 useEffect(()=>{void load().catch(e=>setError(e.message))},[tour]);
 const change=(delta:number)=>setLetters(value=>value.slice(0,cursor)+alphabet[(alphabet.indexOf(value[cursor])+delta+alphabet.length)%alphabet.length]+value.slice(cursor+1));
 const save=async()=>{if(busy||saved)return;setBusy(true);setError('');try{if(STATIC_EDITION){saveLocalScore(localStorage,{id:runId,initials:letters,hero,score,tour});setSaved(true);await load();return}const r=await fetch('/api/highscores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:runId,initials:letters,hero,score,tour})});if(!r.ok)throw new Error('Speichern fehlgeschlagen. Bitte erneut versuchen.');setSaved(true);await load()}catch(e){setError(e instanceof Error?e.message:'Speichern fehlgeschlagen.')}finally{setBusy(false)}};
 const live=useRef({change,save,cursor,saved,busy,onDone});live.current={change,save,cursor,saved,busy,onDone};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLButtonElement&&e.key==='Enter')return;if(live.current.busy)return;if(e.key==='Enter'){e.preventDefault();if(live.current.saved)live.current.onDone();else void live.current.save()}else if(!live.current.saved){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setCursor(v=>(v+(e.key==='ArrowLeft'?2:1))%3)}else if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();live.current.change(e.key==='ArrowUp'?1:-1)}else if(/^[a-z0-9]$/i.test(e.key)){e.preventDefault();setLetters(v=>v.slice(0,live.current.cursor)+e.key.toUpperCase()+v.slice(live.current.cursor+1));setCursor(v=>(v+1)%3)}}};window.addEventListener('keydown',key);let held=true,dir=0,next=0;const timer=setInterval(()=>{const pad=Array.from(navigator.getGamepads?.()??[]).find(p=>p?.connected);if(!pad)return;const b=(n:number)=>pad.buttons[n]?.pressed,confirm=!!(b(0)||b(9)),direction=b(14)||pad.axes[0]<-.5?-1:b(15)||pad.axes[0]>.5?1:b(12)||pad.axes[1]<-.5?2:b(13)||pad.axes[1]>.5?-2:0;if(!live.current.busy){if(confirm&&!held){if(live.current.saved)live.current.onDone();else void live.current.save()}if(direction&&!live.current.saved&&(dir!==direction||Date.now()>next)){if(Math.abs(direction)===1)setCursor(v=>(v+direction+3)%3);else live.current.change(direction>0?1:-1);next=Date.now()+180}}held=confirm;dir=direction},50);return()=>{window.removeEventListener('keydown',key);clearInterval(timer)}},[]);
 return <section className="highscore-screen scanlines"><div className="victory-stars" aria-hidden="true">✦ ✧ ✦ ✧ ✦</div><h1>CONGRATULATIONS!</h1><p>ARCADE CLEAR · {fighter(hero).name.toUpperCase()}</p><div className="score-columns"><div className="score-hero"><FighterPortrait id={hero}/><strong>{score.toString().padStart(7,'0')}</strong><span>FINAL SCORE</span></div><div className="score-entry"><p>{STATIC_EDITION?'LOKALE RANGLISTE · AUF DIESEM GERÄT':'ONLINE-RANGLISTE'}</p><h2>{saved?'DEIN NAME BLEIBT':'TRAGE DEINE INITIALEN EIN'}</h2><div className="initials" aria-label="Highscore-Initialen">{letters.split('').map((letter,i)=><div key={i} className={cursor===i?'active':''}><button disabled={saved||busy} aria-label={`Zeichen ${i+1} erhöhen`} onClick={()=>{setCursor(i);setLetters(v=>v.slice(0,i)+alphabet[(alphabet.indexOf(v[i])+1)%36]+v.slice(i+1))}}>▲</button><button disabled={saved||busy} aria-label={`Zeichen ${i+1}: ${letter}`} onClick={()=>setCursor(i)}>{letter}</button><button disabled={saved||busy} aria-label={`Zeichen ${i+1} verringern`} onClick={()=>{setCursor(i);setLetters(v=>v.slice(0,i)+alphabet[(alphabet.indexOf(v[i])+35)%36]+v.slice(i+1))}}>▼</button></div>)}</div><p>← → Position · ↑ ↓ Buchstabe · ENTER / A bestätigen</p><button className="arcade-button" disabled={busy} onClick={()=>saved?onDone():void save()}>{busy?'WIRD GESPEICHERT …':saved?'WEITER →':'HIGHSCORE EINTRAGEN'}</button>{error&&<p role="alert">{error}</p>}<ol className="highscore-list" aria-label="Highscore-Rangliste">{rows.slice(0,5).map((row,i)=><li key={i}><span>{i+1}.</span><b>{row.initials}</b><span>{fighter(row.hero)?.short??row.hero}</span><strong>{row.score.toString().padStart(7,'0')}</strong></li>)}</ol>{!rows.length&&<p>Der erste Platz wartet auf dich.</p>}<button className="text-button" onClick={onDone}>OHNE WEITEREN EINTRAG WEITER</button></div></div></section>;
}
