import {neutral,type Input} from './combat.ts';
export const KEYMAP=[{left:'KeyA',right:'KeyD',down:'KeyS',jump:'KeyW',punch:'KeyF',kick:'KeyG',block:'KeyH',parry:'KeyQ',ultra:'KeyR',tag:'KeyE'},{left:'ArrowLeft',right:'ArrowRight',down:'ArrowDown',jump:'ArrowUp',punch:'KeyJ',kick:'KeyK',block:'KeyL',parry:'KeyI',ultra:'KeyO',tag:'KeyP'}] as const;
export function padInput(pad:Gamepad|null|undefined):Input{const out=neutral();if(!pad?.connected)return out;const b=(n:number)=>pad.buttons[n]?.pressed??false;out.left=(pad.axes[0]??0)<-.35||b(14);out.right=(pad.axes[0]??0)>.35||b(15);out.down=(pad.axes[1]??0)>.5||b(13);out.jump=b(0)||b(12);out.punch=b(2);out.kick=b(1);out.block=b(4);out.parry=b(5);out.ultra=b(3);out.tag=b(6);return out;}
export class Controls {held=new Set<string>();tapped=new Set<string>();padPause=[false,false];touch:Input=neutral();onPause:()=>void;down:(e:KeyboardEvent)=>void;up:(e:KeyboardEvent)=>void;blur:()=>void;
 playerPads?:[number|null,number|null];
 constructor(onPause:()=>void,playerPads?:[number|null,number|null]){this.playerPads=playerPads;this.onPause=onPause;this.down=e=>{if(e.target instanceof HTMLInputElement)return;if(e.code==='Escape'&&!e.repeat){this.clear();onPause();}if(KEYMAP.some(m=>Object.values(m).includes(e.code as never))){e.preventDefault();this.held.add(e.code);if(!e.repeat)this.tapped.add(e.code);}};this.up=e=>this.held.delete(e.code);this.blur=()=>{this.clear();onPause();};window.addEventListener('keydown',this.down);window.addEventListener('keyup',this.up);window.addEventListener('blur',this.blur);}
 read(index:number):Input{const padIndex=this.playerPads?this.playerPads[index]:index,pad=padIndex===null?null:navigator.getGamepads?.()[padIndex],input=padInput(pad),pause=!!pad?.buttons[9]?.pressed;if(pause&&!this.padPause[index]){this.clear();this.onPause()}this.padPause[index]=pause;const map=KEYMAP[index];for(const key of Object.keys(map) as (keyof Input)[]){input[key]=input[key]||this.held.has(map[key])||this.tapped.has(map[key])||(index===0&&this.touch[key]);this.tapped.delete(map[key])}return input;}
 clear(){this.held.clear();this.tapped.clear();this.touch=neutral();}
 destroy(){window.removeEventListener('keydown',this.down);window.removeEventListener('keyup',this.up);window.removeEventListener('blur',this.blur);}
}
