'use client';
import {useEffect,useRef,useState} from 'react';
import {HEROES,STATIONS,fighter,type FighterId} from './data';
import {FighterPortrait} from './FighterPortrait';
import {NetworkSession,gatherIce} from './network';
import type {BattleConfig} from './scene';
async function api(body:unknown){const r=await fetch('/api/online',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json() as Promise<{code:string;token:string}>}
export function OnlineScreen({onReady,onBack,pad}:{onReady:(config:BattleConfig)=>void;onBack:()=>void;pad:number|null}){
 const [hero,setHero]=useState<FighterId>('ed'),[arena,setArena]=useState('park-9'),[code,setCode]=useState(''),[invitation,setInvitation]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const peer=useRef<RTCPeerConnection|null>(null),cancelled=useRef(false),handedOff=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{cancelled.current=false;return()=>{cancelled.current=true;if(timer.current)clearTimeout(timer.current);if(!handedOff.current)peer.current?.close()}},[]);
 const connect=(channel:RTCDataChannel,side:0|1,config:Omit<BattleConfig,'network'>)=>{if(cancelled.current)return;handedOff.current=true;onReady({...config,network:new NetworkSession(peer.current!,channel,side),playerPads:[pad,null]})};
 const begin=async(host:boolean)=>{setBusy(true);setError('');setInvitation('');if(timer.current)clearTimeout(timer.current);setStatus('VERBINDUNG WIRD VORBEREITET …');peer.current?.close();try{
  const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});peer.current=pc;
  pc.addEventListener('connectionstatechange',()=>{if(pc.connectionState==='failed'){setError('Direkte Verbindung nicht möglich. Bitte in einem anderen Netzwerk versuchen.');setBusy(false)}});
  timer.current=setTimeout(()=>{if(peer.current===pc&&!handedOff.current&&!cancelled.current){pc.close();setError('Einladung abgelaufen. Bitte erneut verbinden.');setBusy(false)}},600000);
  if(host){
   const channel=pc.createDataChannel('super-mack-fighters',{ordered:true});let guest:FighterId|undefined;
   channel.onopen=()=>{const config:BattleConfig={p1:hero,p2:guest!,stationId:arena,cpu:false,difficulty:0,turbo:1.18,parry:true,partners:[null,null],costumes:['classic','classic']};channel.send(JSON.stringify({type:'start',config}));connect(channel,0,config)};
   await pc.setLocalDescription(await pc.createOffer());await gatherIce(pc);if(cancelled.current)return;
   const created=await api({action:'create',offer:pc.localDescription,config:{p1:hero,stationId:arena}});setInvitation(created.code);setStatus('WARTE AUF SPIELER 2');
   const poll=async()=>{if(cancelled.current||handedOff.current||pc.connectionState==='closed')return;try{const r=await fetch('/api/online?code='+created.code,{headers:{Authorization:'Bearer '+created.token}});if(!r.ok)throw new Error(await r.text());const result=await r.json() as {answer:{hero:FighterId;description:RTCSessionDescriptionInit}|null};if(result.answer){guest=result.answer.hero;await pc.setRemoteDescription(result.answer.description);setStatus('SPIELER 2 VERBINDET …')}else timer.current=setTimeout(poll,1500)}catch(e){setError(e instanceof Error?e.message:'Verbindung fehlgeschlagen');setBusy(false)}};void poll();
  }else{
   const r=await fetch('/api/online?code='+encodeURIComponent(code));if(!r.ok)throw new Error(await r.text());const room=await r.json() as {offer:RTCSessionDescriptionInit};
   pc.ondatachannel=e=>{const channel=e.channel;channel.addEventListener('message',function start(event){try{const m=JSON.parse(event.data);if(m.type!=='start')return;const c=m.config;if(!HEROES.some(f=>f.id===c.p1)||c.p2!==hero||!STATIONS.some(s=>s.id===c.stationId))throw new Error();channel.removeEventListener('message',start);connect(channel,1,{p1:c.p1,p2:hero,stationId:c.stationId,cpu:false,difficulty:0,turbo:1.18,parry:true,partners:[null,null],costumes:['classic','classic']})}catch{setError('Die Kampfeinladung ist ungültig.');pc.close()}})};
   await pc.setRemoteDescription(room.offer);await pc.setLocalDescription(await pc.createAnswer());await gatherIce(pc);if(cancelled.current)return;await api({action:'join',code,hero,answer:pc.localDescription});setStatus('VERBINDUNG ZUM GEGNER …');
  }
 }catch(e){if(!cancelled.current){setError(e instanceof Error?e.message:'Verbindung fehlgeschlagen');setBusy(false);peer.current?.close()}}};
 const move=(delta:number)=>setHero(HEROES[(HEROES.findIndex(f=>f.id===hero)+delta+HEROES.length)%HEROES.length].id);
 return <section className="online-screen scanlines"><h1>ONLINE</h1><p>Einladung senden · Gemeinsam in die Arena</p><div className="online-columns"><div className="online-fighter"><FighterPortrait id={hero}/><div className="choice-buttons"><button disabled={busy} aria-label="Vorherige Online-Figur" onClick={()=>move(-1)}>◀</button><b>{fighter(hero).name}</b><button disabled={busy} aria-label="Nächste Online-Figur" onClick={()=>move(1)}>▶</button></div></div><div className="online-panel"><label>ARENA</label><div className="choice-buttons"><button disabled={busy} aria-label="Vorherige Online-Arena" onClick={()=>setArena(STATIONS[(STATIONS.findIndex(s=>s.id===arena)+20)%21].id)}>◀</button><span>{STATIONS.find(s=>s.id===arena)?.name}</span><button disabled={busy} aria-label="Nächste Online-Arena" onClick={()=>setArena(STATIONS[(STATIONS.findIndex(s=>s.id===arena)+1)%21].id)}>▶</button></div><button className="arcade-button" disabled={busy} onClick={()=>void begin(true)}>EINLADUNG ERSTELLEN</button>{invitation&&<><output className="invitation-code" aria-label="Einladungscode">{invitation}</output><p>Spieler 2 öffnet dieses Spiel, wählt ONLINE und gibt den Code ein. Gültig für zehn Minuten.</p></>}<label htmlFor="room-code">MIT CODE BEITRETEN</label><input id="room-code" disabled={busy} value={code} maxLength={10} autoComplete="off" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/><button className="arcade-button secondary" disabled={busy||code.length!==10} onClick={()=>void begin(false)}>BEITRETEN</button><p role="status">{status}</p>{error&&<p role="alert">{error}</p>}<p>1 gegen 1 · Turbo · Parry an. Beide benutzen die Steuerung von Spieler 1 auf ihrem Gerät. Manche Netzwerke blockieren die Direktverbindung.</p></div></div><button className="arcade-button secondary" onClick={onBack}>ZURÜCK</button></section>;
}
