'use client';
import {useEffect,useRef,useState} from 'react';
import {HEROES,STATIONS,fighter,type FighterId} from './data';
import {FighterPortrait} from './FighterPortrait';
import {NetworkSession,gatherIce} from './network';
import {onlineError} from './online-error';
import type {BattleConfig} from './scene';
async function api(body:unknown,signal?:AbortSignal){const r=await fetch('/api/online',{signal,method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(onlineError(r.status,await r.text()));return r.json() as Promise<{code:string;token:string}>}
export function OnlineScreen({onReady,onBack,pad}:{onReady:(config:BattleConfig)=>void;onBack:()=>void;pad:number|null}){
 const [hero,setHero]=useState<FighterId>('ed'),[arena,setArena]=useState('park-9'),[code,setCode]=useState(''),[invitation,setInvitation]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const peer=useRef<RTCPeerConnection|null>(null),cancelled=useRef(false),handedOff=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),pollTimer=useRef<ReturnType<typeof setTimeout>|null>(null),attempt=useRef(0),pending=useRef<AbortController|null>(null);
 const clearTimers=()=>{if(timer.current)clearTimeout(timer.current);if(pollTimer.current)clearTimeout(pollTimer.current);timer.current=null;pollTimer.current=null};
 useEffect(()=>{cancelled.current=false;return()=>{cancelled.current=true;attempt.current++;pending.current?.abort();clearTimers();if(!handedOff.current)peer.current?.close()}},[]);
 const connect=(channel:RTCDataChannel,side:0|1,config:Omit<BattleConfig,'network'>)=>{if(cancelled.current)return;handedOff.current=true;clearTimers();pending.current?.abort();onReady({...config,network:new NetworkSession(peer.current!,channel,side),playerPads:[pad,null]})};
 const begin=async(host:boolean)=>{const run=++attempt.current;pending.current?.abort();const request=new AbortController();pending.current=request;const current=()=>!cancelled.current&&run===attempt.current&&!handedOff.current;const fail=(message:string)=>{if(!current())return;clearTimers();request.abort();peer.current?.close();setError(message);setStatus('');setBusy(false)};setBusy(true);setError('');setInvitation('');clearTimers();setStatus('VERBINDUNG WIRD VORBEREITET …');peer.current?.close();try{
  if(typeof RTCPeerConnection==='undefined')throw Error('Dieser Browser unterstützt keine direkten Online-Duelle.');
  const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});peer.current=pc;
  pc.addEventListener('connectionstatechange',()=>{if(current()&&pc.connectionState==='failed')fail('Direkte Verbindung nicht möglich. Bitte in einem anderen Netzwerk versuchen.')});
  timer.current=setTimeout(()=>{if(current())fail('Einladung abgelaufen. Bitte erneut verbinden.')},600000);
  if(host){
   const channel=pc.createDataChannel('super-mack-fighters',{ordered:true});let guest:FighterId|undefined;
   channel.onopen=()=>{if(!current()||!guest)return;const config:BattleConfig={p1:hero,p2:guest!,stationId:arena,cpu:false,difficulty:0,turbo:1.18,parry:true,partners:[null,null],costumes:['classic','classic']};channel.send(JSON.stringify({type:'start',config}));connect(channel,0,config)};
   await pc.setLocalDescription(await pc.createOffer());await gatherIce(pc);if(!current())return;
   const created=await api({action:'create',offer:pc.localDescription,config:{p1:hero,stationId:arena}},request.signal);if(!current())return;setInvitation(created.code);setStatus('WARTE AUF SPIELER 2');
   const poll=async()=>{if(!current()||pc.connectionState==='closed')return;try{const r=await fetch('/api/online?code='+created.code,{signal:request.signal,headers:{Authorization:'Bearer '+created.token}});if(!r.ok)throw new Error(onlineError(r.status,await r.text()));const result=await r.json() as {answer:{hero:FighterId;description:RTCSessionDescriptionInit}|null};if(!current())return;if(result.answer){guest=result.answer.hero;await pc.setRemoteDescription(result.answer.description);setStatus('SPIELER 2 VERBINDET …')}else pollTimer.current=setTimeout(poll,1500)}catch(e){fail(e instanceof Error?e.message:'Verbindung fehlgeschlagen')}};void poll();
  }else{
   const r=await fetch('/api/online?code='+encodeURIComponent(code),{signal:request.signal});if(!r.ok)throw new Error(onlineError(r.status,await r.text()));const room=await r.json() as {offer:RTCSessionDescriptionInit};if(!current())return;
   pc.ondatachannel=e=>{const channel=e.channel;channel.addEventListener('message',function start(event){if(!current())return;try{const m=JSON.parse(event.data);if(m.type!=='start')return;const c=m.config;if(!HEROES.some(f=>f.id===c.p1)||c.p2!==hero||!STATIONS.some(s=>s.id===c.stationId))throw new Error();channel.removeEventListener('message',start);connect(channel,1,{p1:c.p1,p2:hero,stationId:c.stationId,cpu:false,difficulty:0,turbo:1.18,parry:true,partners:[null,null],costumes:['classic','classic']})}catch{fail('Die Kampfeinladung ist ungültig.')}})};
   await pc.setRemoteDescription(room.offer);await pc.setLocalDescription(await pc.createAnswer());await gatherIce(pc);if(!current())return;await api({action:'join',code,hero,answer:pc.localDescription},request.signal);if(!current())return;setStatus('VERBINDUNG ZUM GEGNER …');
  }
 }catch(e){fail(e instanceof Error?e.message:'Verbindung fehlgeschlagen')}};
 const move=(delta:number)=>setHero(HEROES[(HEROES.findIndex(f=>f.id===hero)+delta+HEROES.length)%HEROES.length].id);
 return <section className="online-screen scanlines"><h1>ONLINE</h1><p>Einladung senden · Gemeinsam in die Arena</p><div className="online-columns"><div className="online-fighter"><FighterPortrait id={hero}/><div className="choice-buttons"><button disabled={busy} aria-label="Vorherige Online-Figur" onClick={()=>move(-1)}>◀</button><b>{fighter(hero).name}</b><button disabled={busy} aria-label="Nächste Online-Figur" onClick={()=>move(1)}>▶</button></div></div><div className="online-panel"><label>ARENA</label><div className="choice-buttons"><button disabled={busy} aria-label="Vorherige Online-Arena" onClick={()=>setArena(STATIONS[(STATIONS.findIndex(s=>s.id===arena)+20)%21].id)}>◀</button><span>{STATIONS.find(s=>s.id===arena)?.name}</span><button disabled={busy} aria-label="Nächste Online-Arena" onClick={()=>setArena(STATIONS[(STATIONS.findIndex(s=>s.id===arena)+1)%21].id)}>▶</button></div><button className="arcade-button" disabled={busy} onClick={()=>void begin(true)}>EINLADUNG ERSTELLEN</button>{invitation&&<><output className="invitation-code" aria-label="Einladungscode">{invitation}</output><p>Spieler 2 öffnet dieses Spiel, wählt ONLINE und gibt den Code ein. Gültig für zehn Minuten.</p></>}<label htmlFor="room-code">MIT CODE BEITRETEN</label><input id="room-code" disabled={busy} value={code} maxLength={10} autoComplete="off" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/><button className="arcade-button secondary" disabled={busy||code.length!==10} onClick={()=>void begin(false)}>BEITRETEN</button><p role="status">{status}</p>{error&&<p role="alert">{error}</p>}<p>1 gegen 1 · Turbo · Parry an. Beide benutzen die Steuerung von Spieler 1 auf ihrem Gerät. Manche Netzwerke blockieren die Direktverbindung.</p></div></div><button className="arcade-button secondary" onClick={onBack}>ZURÜCK</button></section>;
}
