'use client';
import {useEffect,useRef,useState} from 'react';
import {loadCostumeSheet} from './costume-art';
import type {Costume} from './rules';
import {fighter,station,STATIONS,type FighterId} from './data';
import {WORLD_WIDTH,WORLD_HEIGHT,cameraTarget,DISTRICTS} from './park-layout';
import {buildParkTexture,WORLD_ART} from './park-render';
import {advanceWalkPhase,walkFrame} from './walk-animation';
import {arcadeOpponent,arcadeBoss,bossLabel} from './arcade-ladder';
import {arenaGate,distance,findWalkRoute,NODES,PARK_ENTRY,projectToPath,routeLength,walkStep,type Point} from './park-world';

type Props={hero:FighterId;costume?:Costume;route:string[];index:number;position?:Point|null;onPosition:(p:Point)=>void;onEnter:()=>void;onMap:()=>void;onHome:()=>void;onFull:()=>void};
export function ParkWorld(props:Props){const canvas=useRef<HTMLCanvasElement>(null),actions=useRef({go:()=>{},pause:()=>{},map:()=>{}}),latest=useRef(props);latest.current=props;const [near,setNear]=useState(false),[remaining,setRemaining]=useState(0),[paused,setPaused]=useState(false),[loaded,setLoaded]=useState(false),[localName,setLocalName]=useState('Haupteingang');const target=station(props.route[props.index]);
 useEffect(()=>{const el=canvas.current!,ctx=el.getContext('2d')!;let running=true,frame=0,previous=0,clock=0,lastUi=0,stopped=false,walking=false,walkPhase=0,face=1,padConfirm=false,padMenu=false,padMap=false;let player={...projectToPath(props.position??(props.index?arenaGate(props.route[props.index-1]):PARK_ENTRY)).point},camera=cameraTarget(player),travel:Point[]=[];const keys=new Set<string>(),destination=arenaGate(props.route[props.index]),routeGates=props.route.map(id=>({id,p:arenaGate(id)}));const paths=STATIONS.filter(s=>s.kind==='Themenbereich').map(s=>({s,p:arenaGate(s.id)}));
 const motionSprite=new Image();let motionReady=false,costumeMotion:HTMLCanvasElement|null=null;motionSprite.onload=()=>motionReady=true;motionSprite.src=`/assets/motion/${props.hero}.png`;void loadCostumeSheet(props.hero,props.costume??'classic','motion').then(sheet=>{if(running)costumeMotion=sheet}).catch(()=>{});const map=new Image(),sprite=new Image(),walkSprite=new Image(),visitors=new Image();let world:HTMLCanvasElement|null=null;let mapReady=false,spriteReady=false,walkReady=false,visitorsReady=false;map.onload=()=>{world=buildParkTexture(map);mapReady=true;setLoaded(true)};map.onerror=()=>setLoaded(true);map.src=WORLD_ART;sprite.onload=()=>spriteReady=true;sprite.src=`/assets/${props.hero}.png`;walkSprite.onload=()=>walkReady=true;walkSprite.src=`/assets/walk/${props.hero}.png`;visitors.onload=()=>visitorsReady=true;visitors.src='/assets/visitors.png';
 let costumeAction:HTMLCanvasElement|null=null,costumeWalk:HTMLCanvasElement|null=null;void loadCostumeSheet(props.hero,props.costume??'classic').then(sheet=>{if(running)costumeAction=sheet}).catch(()=>{});void loadCostumeSheet(props.hero,props.costume??'classic','walk').then(sheet=>{if(running)costumeWalk=sheet}).catch(()=>{});
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const zoom=2;
 const pause=(value:boolean)=>{stopped=value;setPaused(value);keys.clear();previous=0};
 const enter=()=>{if(distance(player,destination)<19&&!stopped)latest.current.onEnter()};
 const go=()=>{travel=findWalkRoute(player,destination);pause(false)};
 const showMap=()=>{latest.current.onPosition({...player});latest.current.onMap()};
 actions.current={go,pause:()=>pause(!stopped),map:showMap};
 const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLButtonElement&&['Enter','Space'].includes(e.code))return;const used=['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','KeyM','Enter','KeyE','KeyF','Escape','ShiftLeft','ShiftRight'];if(!used.includes(e.code))return;e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){pause(!stopped);return}if(stopped)return;if(e.code==='KeyM'){showMap();return}if(['Enter','KeyE','KeyF'].includes(e.code)){enter();return}keys.add(e.code);travel=[]};
 const up=(e:KeyboardEvent)=>keys.delete(e.code),blur=()=>pause(true);
 const pointer=(e:PointerEvent)=>{if(stopped)return;const rect=el.getBoundingClientRect(),screenX=(e.clientX-rect.left)*1280/rect.width,screenY=(e.clientY-rect.top)*720/rect.height;if(screenX>1010&&screenY>495){showMap();return}const click={x:camera.x+(screenX-640)/zoom,y:camera.y+(screenY-360)/zoom};const nearest=projectToPath(click);if(nearest.distance<35)travel=findWalkRoute(player,nearest.point);el.focus({preventScroll:true})};
 el.addEventListener('pointerdown',pointer);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 const npcs=Array.from({length:14},(_,i)=>{const nodes=Object.values(NODES),from=nodes[(i*7+9)%nodes.length],to=nodes[(i*11+24)%nodes.length];return {path:findWalkRoute(from,to),speed:8+i%4*2,offset:i*17,type:i%4}});
 const drawSprite=(img:CanvasImageSource,x:number,y:number,cell:number,size:number,flip:boolean,alpha=1,columns=4)=>{ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.globalAlpha=alpha;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,cell%columns*256,Math.floor(cell/columns)*256,256,256,-size/2,-size,size,size);ctx.restore()};
 const draw=(time:number)=>{if(!running)return;frame=requestAnimationFrame(draw);const dt=Math.min((time-(previous||time))/1000,.04);previous=time;if(!stopped){clock+=dt;const pad=Array.from(navigator.getGamepads?.()??[]).find(p=>p?.connected),button=(n:number)=>pad?.buttons[n]?.pressed??false;const confirm=button(0),menu=button(9),mapKey=button(8);if(confirm&&!padConfirm)enter();if(menu&&!padMenu)pause(true);if(mapKey&&!padMap)showMap();padConfirm=confirm;padMenu=menu;padMap=mapKey;let dx=Number(keys.has('KeyD')||keys.has('ArrowRight')||button(15))-Number(keys.has('KeyA')||keys.has('ArrowLeft')||button(14)),dy=Number(keys.has('KeyS')||keys.has('ArrowDown')||button(13))-Number(keys.has('KeyW')||keys.has('ArrowUp')||button(12));if(Math.abs(pad?.axes[0]??0)>.25)dx=pad!.axes[0];if(Math.abs(pad?.axes[1]??0)>.25)dy=pad!.axes[1];if(dx||dy)travel=[];const speed=(keys.has('ShiftLeft')||keys.has('ShiftRight')||button(1)?164:112)*dt;const before={...player};if(travel.length){const node=travel[0],d=distance(player,node);if(d<=speed){player={...node};travel.shift()}else player={x:player.x+(node.x-player.x)/d*speed,y:player.y+(node.y-player.y)/d*speed};}else if(dx||dy){const len=Math.hypot(dx,dy);player=walkStep(player,dx/len*speed,dy/len*speed)}const moved=distance(before,player);walking=moved>.03;walkPhase=walking?advanceWalkPhase(walkPhase,moved,34):0;if(Math.abs(player.x-before.x)>.02)face=player.x>before.x?1:-1;const amount=reduced?1:Math.min(1,dt*8);const targetCamera=cameraTarget(player);camera.x+=(targetCamera.x-camera.x)*amount;camera.y+=(targetCamera.y-camera.y)*amount;if(time-lastUi>180){lastUi=time;setNear(distance(player,destination)<19);setRemaining(Math.round(routeLength(findWalkRoute(player,destination))));const closest=paths.reduce((a,b)=>distance(player,a.p)<distance(player,b.p)?a:b);setLocalName(distance(player,PARK_ENTRY)<25?'Haupteingang':closest.s.name)}}
 ctx.fillStyle='#244c39';ctx.fillRect(0,0,1280,720);ctx.save();ctx.translate(640,360);ctx.scale(zoom,zoom);ctx.translate(-camera.x,-camera.y);ctx.imageSmoothingEnabled=false;if(world)ctx.drawImage(world,0,0);
 DISTRICTS.forEach(d=>{ctx.font='bold 10px "Pixelify Sans",monospace';ctx.textAlign='center';ctx.fillStyle='#10293d';const name=station(d.id).name,w=ctx.measureText(name).width+12;ctx.fillRect(d.x-w/2,d.y+10,w,16);ctx.fillStyle='#fff0b1';ctx.fillText(name,d.x,d.y+22)});
 // A subtle in-world guide follows the traversable path, never crossing a building.
 const guide=travel.length?[player,...travel]:findWalkRoute(player,destination);ctx.lineWidth=2;ctx.strokeStyle='#ffe6a2bb';ctx.setLineDash([2,3]);ctx.lineDashOffset=-clock*5;ctx.beginPath();guide.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);
 routeGates.forEach(({id,p},i)=>{if(i>props.index+1||i<props.index&&routeGates.slice(i+1,props.index+1).some(g=>distance(g.p,p)<1))return;const active=i===props.index;ctx.save();ctx.translate(p.x,p.y);ctx.lineWidth=active?1.7:1;ctx.strokeStyle=active?'#fff0a2':i<props.index?'#a2f0c2':'#cbdceb';ctx.fillStyle=active?'#6c381b99':'#183c5a88';ctx.beginPath();ctx.ellipse(0,0,active?10+Math.sin(clock*3)*1.2:7,active?5:3,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font=`bold ${active?7:5}px "Pixelify Sans",monospace`;ctx.textAlign='center';ctx.lineWidth=2;ctx.strokeStyle='#172a3e';ctx.fillStyle=active?'#ffefb2':'#fff';const label=active?'':i<props.index?'✓':String(i+1);ctx.strokeText(label,0,active?-32:-10);ctx.fillText(label,0,active?-24:-10);if(active){ctx.fillStyle='#ffe6a2';ctx.beginPath();ctx.moveTo(-3,-17);ctx.lineTo(3,-17);ctx.lineTo(0,-12+Math.sin(clock*3));ctx.fill()}ctx.restore()});
 const people:{x:number;y:number;cell:number;flip:boolean;kind:'hero'|'visitor'}[]=[{...player,cell:motionReady?(walking?8+walkFrame(walkPhase,8):Math.floor(clock*12)%8):walking&&walkReady?walkFrame(walkPhase):Math.floor(clock*2)%2,flip:face<0,kind:'hero'}];if(visitorsReady)for(const npc of npcs){const total=routeLength(npc.path);let offset=(clock*npc.speed+npc.offset)%(total*2),reverse=offset>total;if(reverse)offset=total*2-offset;for(let i=1;i<npc.path.length;i++){const a=npc.path[i-1],b=npc.path[i],len=distance(a,b);if(offset<=len){people.push({x:a.x+(b.x-a.x)*offset/len,y:a.y+(b.y-a.y)*offset/len,cell:npc.type*4+Math.floor(clock*6)%4,flip:reverse?b.x>a.x:b.x<a.x,kind:'visitor'});break}offset-=len}}
 people.sort((a,b)=>a.y-b.y).forEach(p=>{ctx.fillStyle=p.kind==='hero'?'#14202766':'#1420273c';ctx.beginPath();ctx.ellipse(p.x,p.y+.5,p.kind==='hero'?6:3,2,0,0,Math.PI*2);ctx.fill();if(p.kind==='hero'&&spriteReady)drawSprite(motionReady?(costumeMotion??motionSprite):walking&&walkReady?(costumeWalk??walkSprite):(costumeAction??sprite),p.x,p.y+1,p.cell,38,p.flip,1,motionReady?8:4);if(p.kind==='visitor')drawSprite(visitors,p.x,p.y+1,p.cell,34,p.flip,.92)});ctx.restore();
 const shade=ctx.createLinearGradient(0,0,0,720);shade.addColorStop(0,'#091525d0');shade.addColorStop(.18,'#09152500');shade.addColorStop(.8,'#09152500');shade.addColorStop(1,'#091525cc');ctx.fillStyle=shade;ctx.fillRect(0,0,1280,720);
 // The overview is a crop of the exact playable world, with the same coordinates.
 ctx.fillStyle='#0c213bef';ctx.fillRect(1020,510,230,142);ctx.strokeStyle='#b8b8cf';ctx.lineWidth=2;ctx.strokeRect(1020,510,230,142);if(world)ctx.drawImage(world,1025,515,220,126);ctx.fillStyle='#ffe6a3';ctx.fillRect(1025+destination.x/WORLD_WIDTH*220-3,515+destination.y/WORLD_HEIGHT*126-3,6,6);ctx.fillStyle='#fff';ctx.fillRect(1025+player.x/WORLD_WIDTH*220-2,515+player.y/WORLD_HEIGHT*126-2,4,4);ctx.strokeStyle='#ffffffaa';ctx.lineWidth=1;ctx.strokeRect(1025+(camera.x-320)/WORLD_WIDTH*220,515+(camera.y-180)/WORLD_HEIGHT*126,640/WORLD_WIDTH*220,360/WORLD_HEIGHT*126);

 };frame=requestAnimationFrame(draw);return()=>{running=false;cancelAnimationFrame(frame);latest.current.onPosition(player);el.removeEventListener('pointerdown',pointer);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);};
 },[props.hero,props.index,props.route,props.costume]);
 return <section className="park-world" aria-label="Begehbare Pixel-Parkwelt"><canvas ref={canvas} width="1280" height="720" tabIndex={0} aria-label="Parkwelt: Mit WASD oder Pfeiltasten laufen. Wege anklicken zum Gehen. Enter betritt die Arena."/><div className="world-top"><div><span>{fighter(props.hero).name.toUpperCase()} · {props.index}/{props.route.length} SIEGE</span><strong>{localName.toUpperCase()}</strong></div><div className="world-objective"><span>{bossLabel(arcadeBoss(props.index,props.route.length))} · {fighter(arcadeOpponent(props.index,props.route.length)).name}</span><strong>{target.name}</strong><small>{near?'EINGANG ERREICHT':'DEM GOLDENEN WEG FOLGEN'}</small></div></div>{!loaded&&<div className="world-loading">DER PARK ÖFFNET …</div>}<div className="world-bottom"><span>✥ WASD / PFEILE <small>LAUFEN · SHIFT RENNEN</small></span><button onClick={()=>actions.current.go()}>▸ ZUM ARENA-EINGANG</button><button onClick={props.onEnter} disabled={!near}>A / ENTER · {near?'ARENA BETRETEN':'ZUM EINGANG LAUFEN'}</button><button onClick={()=>actions.current.map()}>M KARTE</button><button onClick={()=>actions.current.pause()}>Ⅱ</button></div>{paused&&<div className="world-pause"><div><h2>PAUSE</h2><button onClick={()=>actions.current.pause()}>WEITER</button><button onClick={()=>actions.current.map()}>PARKPLAN</button><button onClick={props.onFull}>VOLLBILD</button><button onClick={props.onHome}>HAUPTMENÜ</button></div></div>}</section>;
}
