import test from 'node:test';
import assert from 'node:assert/strict';
import {createMatch,step,neutral,activeHitbox,hurtbox,boxesOverlap,comboName} from './combat.ts';
import {makeBattleConfig,localPlayersReady,newJoinPress} from './match-setup.ts';
import {DEFAULT_RULES} from './rules.ts';
import {FULL_TOUR,HEROES} from './data.ts';
import {cameraTarget,WORLD_HEIGHT,WORLD_WIDTH} from './park-layout.ts';
import {packInput,unpackInput,NetworkSession} from './network.ts';
test('free CPU match uses selected fighter, area and difficulty instead of tour state',()=>{const c=makeBattleConfig({mode:'cpu',p1:'wakala',p2:'max',arena:'park-9',route:FULL_TOUR,index:5,difficulty:.12,rules:DEFAULT_RULES,pads:[null,null]});assert.equal(c.p2,'max');assert.equal(c.stationId,'park-9');assert.equal(c.difficulty,.12);assert.equal(c.cpu,true);assert.deepEqual(c.partners,[null,null])});
test('local humans explicitly join and cannot share a controller or retain a disconnected one',()=>{assert.equal(localPlayersReady(false,[null,null],[]),false);assert.equal(localPlayersReady(true,[null,0],[0]),true);assert.equal(localPlayersReady(true,[0,0],[0]),false);assert.equal(localPlayersReady(true,[0,1],[0]),false);assert.equal(newJoinPress(1,0,true,undefined),false);assert.equal(newJoinPress(0,0,true,false),false);assert.equal(newJoinPress(1,0,true,false),true)});
test('arcade finale chooses the boss in a themed area and training remains open-ended',()=>{const c=makeBattleConfig({mode:'arcade',p1:'ed',p2:'max',arena:'park-9',route:FULL_TOUR,index:20,difficulty:.38,rules:DEFAULT_RULES,pads:[null,null]});assert.equal(c.p2,'graumacher');assert.ok(c.stationId.startsWith('park-'));const m=createMatch('ed','wakala',19,{training:true});for(let i=0;i<150;i++)step(m,[neutral(),neutral()]);const time=m.time;for(let i=0;i<4000;i++)step(m,[neutral(),neutral()]);assert.equal(m.time,time);assert.deepEqual(m.meter,[100,100]);m.actors[1].hp=0;step(m,[neutral(),neutral()]);assert.notEqual(m.phase,'complete');assert.equal(m.actors[1].hp,100)});
test('training hit zones are active only during attack frames and use combat geometry',()=>{const m=createMatch('ed','snorri');const a=m.actors[0],b=m.actors[1];a.action='punch';a.age=7;assert.equal(activeHitbox(a),null);a.age=8;b.x=a.x+70;assert.equal(boxesOverlap(activeHitbox(a)!,hurtbox(b)),true);b.action='crouch';assert.equal(boxesOverlap(activeHitbox(a)!,hurtbox(b)),false);a.age=13;assert.equal(activeHitbox(a),null)});
test('late attack presses buffer for six simulation frames without auto-repeating',()=>{const m=createMatch('ed','snorri');m.phase='fight';m.actors[0].lock=4;m.actors[0].action='hit';step(m,[{...neutral(),punch:true},neutral()]);for(let n=0;n<3;n++)step(m,[neutral(),neutral()]);assert.equal(m.actors[0].action,'punch');for(let n=0;n<50;n++)step(m,[neutral(),neutral()]);assert.equal(m.actors[0].action,'idle')});
test('blocked attacks do not increment a combo; consecutive hits during stun do',()=>{const hit=(blocked:boolean)=>{const m=createMatch('ed','snorri');m.phase='fight';m.actors[0].x=300;m.actors[1].x=370;m.actors[0].action='punch';m.actors[0].lock=25;m.actors[0].age=7;m.actors[0].combo=1;m.actors[1].action=blocked?'block':'hit';m.actors[1].lock=10;step(m,[neutral(),{...neutral(),block:blocked}]);return m};assert.equal(hit(true).actors[0].combo,1);assert.equal(hit(false).actors[0].combo,2);assert.equal(comboName(4),'TURBO COMBO')});
test('close camera follows movement and never reveals outside the pixel world',()=>{const a=cameraTarget({x:900,y:500}),b=cameraTarget({x:1100,y:500});assert.equal(b.x-a.x,200);for(const p of [{x:0,y:0},{x:9999,y:9999}]){const c=cameraTarget(p);assert.ok(c.x>=320&&c.x<=WORLD_WIDTH-320);assert.ok(c.y>=180&&c.y<=WORLD_HEIGHT-180)}});
test('online input transport preserves every control combination',()=>{for(let bits=0;bits<1024;bits++)assert.equal(packInput(unpackInput(bits)),bits)});
test('online peers wait for missing input and simulate identical deterministic frames',()=>{
 class Channel extends EventTarget {readyState='open';other!:Channel;queue:string[]=[];send(text:string){this.other.queue.push(text)}flush(){for(const data of this.queue.splice(0))this.dispatchEvent(new MessageEvent('message',{data}))}close(){this.readyState='closed'}}
 const a=new Channel(),b=new Channel();a.other=b;b.other=a;const peer={close(){}} as RTCPeerConnection;
 const n1=new NetworkSession(peer,a as unknown as RTCDataChannel,0),n2=new NetworkSession(peer,b as unknown as RTCDataChannel,1),m1=createMatch('ed','max'),m2=createMatch('ed','max');n1.ready();n2.ready();a.flush();b.flush();
 for(let round=0;round<1500;round++){for(const [n,m] of [[n1,m1],[n2,m2]] as const){const inputs=n.inputs(()=>({...neutral(),right:n.side===0,left:n.side===1,punch:n.frame%50===0}));if(inputs)step(m,inputs)}if(round%3===0){a.flush();b.flush()}}
 while(n1.frame<n2.frame){a.flush();const i=n1.inputs(neutral);if(!i)break;step(m1,i)}while(n2.frame<n1.frame){b.flush();const i=n2.inputs(neutral);if(!i)break;step(m2,i)}assert.ok(n1.frame>500);assert.equal(n1.frame,n2.frame);assert.deepEqual(m1,m2);n1.destroy();n2.destroy();
});
