import Phaser from 'phaser';
import type {NetworkSession} from './network';
import {fighter,type FighterId,station} from './data.ts';
import {activeHitbox,hurtbox,activeMove,createMatch,step,aiInput,createBrain,TICK,FLOOR,neutral,type Match,type Input} from './combat.ts';
import {stagePhysics} from './stages.ts';
import {loadCostumeSheet} from './costume-art';
import type {Costume} from './rules.ts';
import {Controls} from './input.ts';
import {ArcadeAudio} from './audio.ts';
import {ARENA_ART} from './arena-art.ts';
import {ArenaLife} from './arena-life.ts';
import {advanceWalkPhase,walkFrame} from './walk-animation.ts';
import {motionFrame} from './fighter-animation.ts';
import {bossLabel,type BossRole} from './arcade-ladder.ts';
export interface BattleConfig {boss?:BossRole;network?:NetworkSession;p1:FighterId;p2:FighterId;stationId:string;cpu:boolean;difficulty:number;playerPads?:[number|null,number|null];training?:boolean;parry?:boolean;turbo?:number;partners?:[FighterId|null,FighterId|null];costumes?:[Costume,Costume];}
export interface BattleHandle {training:(options:{boxes?:boolean;dummy?:'stand'|'block'|'cpu';reset?:boolean})=>void;pause:(p:boolean)=>void;touch:(key:keyof Input,value:boolean)=>void;destroy:()=>void;}
export function mountBattle(parent:HTMLElement,config:BattleConfig,audio:ArcadeAudio,onState:(m:Match)=>void,onComplete:(winner:number,points:number)=>void,onPause:()=>void):BattleHandle {
 let boxes=true,dummy:'stand'|'block'|'cpu'='stand';let costumesReady=false,paused=false,match=createMatch(config.p1,config.p2,19,{parry:config.parry,turbo:config.turbo,partners:config.partners,stageId:config.stationId,training:config.training}),accumulator=0,ended=false;const controls=new Controls(()=>{if(!paused){paused=true;config.network?.pause(true);audio.pause(true);onPause();}},config.playerPads),brain=createBrain();
 class Arena extends Phaser.Scene {
  sprites:Phaser.GameObjects.Sprite[]=[];shadows:Phaser.GameObjects.Ellipse[]=[];fx!:Phaser.GameObjects.Graphics;back!:Phaser.GameObjects.Image;floor!:Phaser.GameObjects.Image;life!:ArenaLife;banner!:Phaser.GameObjects.Text;arena=station(config.stationId).arena;
  walkPhases=[0,0];lastX=match.actors.map(a=>a.x);
  preload(){this.load.spritesheet('arena-crowd','/assets/arena-crowd.png',{frameWidth:256,frameHeight:256});this.load.image('arena',ARENA_ART[config.stationId]?.url??`/assets/arena-${this.arena}.png`);for(const id of new Set([config.p1,config.p2,...(config.partners??[]).filter((id):id is FighterId=>id!==null)])){if(!id)continue;if(!this.textures.exists(id))this.load.spritesheet(id,`/assets/${id}.png`,{frameWidth:256,frameHeight:256});this.load.spritesheet(id+'-walk',`/assets/walk/${id}.png`,{frameWidth:256,frameHeight:256});this.load.spritesheet(id+'-motion',`/assets/motion/${id}.png`,{frameWidth:256,frameHeight:256});}}
  create(){const jobs:Promise<void>[]=[];for(const side of [0,1]){const costume=config.costumes?.[side]??'classic';if(costume==='classic')continue;for(const id of match.teams[side])for(const kind of ['action','walk','motion'] as const){jobs.push(loadCostumeSheet(id,costume,kind).then(sheet=>{if(!this.sys.isActive())return;const key='costume-'+side+'-'+id+(kind==='action'?'':'-'+kind);if(!this.textures.exists(key))this.textures.addSpriteSheet(key,this.textures.addCanvas(key,sheet)!,{frameWidth:256,frameHeight:256})}))}}void Promise.all(jobs).then(()=>{costumesReady=true;config.network?.ready();onState(match)}).catch(error=>{console.error(error);costumesReady=true;config.network?.ready();onState(match)});this.back=this.add.image(480,270,'arena');const source=this.textures.get('arena').getSourceImage() as HTMLImageElement;const photo=!!ARENA_ART[config.stationId];if(photo){this.textures.get('arena').setFilter(Phaser.Textures.FilterMode.NEAREST);const scale=Math.max(980/source.width,552/source.height);this.back.setDisplaySize(source.width*scale,source.height*scale);this.add.rectangle(480,508,960,65,0x162337,.07);}else{this.back.setDisplaySize(1060,600);this.textures.get('arena').add('ground',0,0,Math.floor(source.height*.79),source.width,Math.floor(source.height*.21));this.floor=this.add.image(480,483,'arena','ground').setDisplaySize(1120,125);}this.life=new ArenaLife(this,config.stationId);this.shadows=match.actors.map(a=>this.add.ellipse(a.x,FLOOR+3,112,20,0x151728,.35));
   this.sprites=match.actors.map(a=>this.add.sprite(a.x,FLOOR+a.y,a.id,0).setOrigin(.5,246/256).setDisplaySize(274,274));this.fx=this.add.graphics();this.banner=this.add.text(480,190,'',{fontFamily:'Pixelify Sans',fontSize:'42px',fontStyle:'bold',color:'#fff2ca',stroke:'#151528',strokeThickness:9,align:'center'}).setOrigin(.5).setDepth(30);audio.setArena(config.stationId,!!config.boss);audio.sound('select');
  }
  update(_time:number,delta:number){if(paused||!costumesReady)return;accumulator+=Math.min(delta/1000,.1)*match.rules.turbo;while(accumulator>=TICK){const networkInputs=config.network?.inputs(()=>controls.read(0));if(config.network&&!networkInputs){accumulator=Math.min(accumulator,TICK);break}accumulator-=TICK;const p1=networkInputs?.[0]??controls.read(0),p2=networkInputs?.[1]??(config.training&&dummy!=='cpu'?{...neutral(),block:dummy==='block'}:config.cpu?aiInput(match,1,config.difficulty,brain):controls.read(1));step(match,[p1,p2]);for(const event of match.events){audio.sound(event.type);if(event.type==='ko'){if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches){this.cameras.main.flash(150,255,231,195);this.cameras.main.shake(230,.012);}this.burst(480,270,0xffdf80);}if(event.type==='hit'||event.type==='ko'||event.type==='win')this.life.cheer(match.tick);if(event.type==='hit'){if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)this.cameras.main.shake(85,.003);this.burst(event.x??480,event.y??340,0xffdd65);}if(event.type==='ultra'){if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)this.cameras.main.flash(160,180,200,255);this.callout(event.label??'ULTRA!',event.player??0);this.life.cheer(match.tick);}
    if(event.type==='parry'){this.burst(event.x??480,event.y??340,0x72ffff);this.callout('PARRY!',event.player??0);}
    if(event.type==='tag'){this.burst(event.x??480,event.y??340,0xffe290);this.callout(event.label??'WECHSEL',event.player??0);}
    if(event.type==='block')this.burst(event.x??480,event.y??340,0x7eedff);if(event.type==='special'&&event.label)this.callout(event.label,event.player??0);}
    if(match.tick%4===0||match.phase==='complete')onState(match);
    if(match.phase==='complete'&&!ended){ended=true;onComplete(match.winner??0,Math.round(1000+match.score[0]*500+Math.max(0,match.time)/60*10+match.actors[0].hp*20+(match.actors[0].hp===100?1000:0)));}
   }
   const center=(match.actors[0].x+match.actors[1].x)/2-480;this.back.x=480-center*.055;if(this.floor)this.floor.x=480-center*.14;this.fx.clear();this.life.draw(match.tick,center*.055);const stage=stagePhysics(config.stationId,match.tick),ground=FLOOR+stage.floorOffset;
   if(stage.effect==='water-platform'){this.fx.fillStyle(0xa67943,1);this.fx.fillRect(45,ground+3,870,10);this.fx.lineStyle(3,0xebd095,1);this.fx.lineBetween(45,ground+3,915,ground+3);this.fx.lineStyle(1,0x805e3a,.65);for(let x=45;x<915;x+=58)this.fx.lineBetween(x,ground+4,x,ground+12);}
   if(stage.effect==='wind'){this.fx.lineStyle(2,0xe5f4ff,.5);const x=470+stage.wind*.5;this.fx.lineBetween(440,135,520,135);this.fx.lineBetween(x,130,x+Math.sign(stage.wind)*8,135);this.fx.lineBetween(x,140,x+Math.sign(stage.wind)*8,135);}
   match.actors.forEach((a,i)=>{const s=this.sprites[i],age=a.age;let frame=0;if(a.action==='idle')frame=Math.floor(age/16)%2;if(a.action==='walk')frame=2+Math.floor(age/8)%2;if(a.action==='jump')frame=4;if(a.action==='crouch')frame=5;if(a.action==='punch'||a.action==='airpunch')frame=age<8?6:7;if(a.action==='kick'||a.action==='airkick')frame=age<14?8:9;if(a.action==='block')frame=10;if(a.action==='hit')frame=11;if(a.action==='special')frame=age<activeMove(a).startup?12:13;if(a.action==='ultra')frame=age<28?12:13;if(a.action==='parry')frame=10;if(a.action==='tag')frame=0;if(a.action==='defeat')frame=14;if(a.action==='victory')frame=15;
    const dx=a.x-this.lastX[i];this.lastX[i]=a.x;const isWalking=a.action==='walk'&&this.textures.exists(a.id+'-walk');
    if(isWalking){this.walkPhases[i]=advanceWalkPhase(this.walkPhases[i],Math.abs(dx),160,dx*a.face<0?-1:1);frame=walkFrame(this.walkPhases[i]);}else this.walkPhases[i]=0;
    const breath=a.action==='idle'?Math.sin(age*.095)*.009:0;
    const motion=motionFrame(a.action,age,this.walkPhases[i]),hasMotion=motion!==null&&this.textures.exists(a.id+'-motion');if(hasMotion)frame=motion;const suffix=hasMotion?'-motion':isWalking?'-walk':'';const costumeKey='costume-'+i+'-'+a.id+suffix;const texture=this.textures.exists(costumeKey)?costumeKey:a.id+suffix;const landing=a.action==='land'?.045*(1-Math.min(1,age/6)):0;s.setTexture(texture,frame).setPosition(Math.round(a.x),Math.round(ground+a.y)).setFlipX(a.face<0).setDisplaySize(274*(1-breath*.4+landing),274*(1+breath-landing));s.alpha=a.action==='hit'&&Math.floor(match.tick/3)%2===0?.55:1;this.shadows[i].setPosition(a.x,ground+5).setScale(1+a.y/500).setAlpha(.35+a.y/700);
    if(a.action==='special'&&activeMove(a).kind==='dash'&&age>18&&age<34&&match.tick%4===0){const echo=this.add.sprite(s.x-a.face*14,s.y,texture,frame).setOrigin(.5,246/256).setDisplaySize(274,274).setFlipX(a.face<0).setTint(Phaser.Display.Color.HexStringToColor(fighter(a.id).color).color).setAlpha(.35).setDepth(1);this.tweens.add({targets:echo,alpha:0,duration:180,onComplete:()=>echo.destroy()});}
    if(a.specialCd===0&&a.action==='idle'&&match.tick%12<6){this.fx.lineStyle(2,Phaser.Display.Color.HexStringToColor(fighter(a.id).color).color,.5);this.fx.strokeEllipse(a.x,FLOOR+3,120,22);}
    if(a.action==='ultra'){const col=Phaser.Display.Color.HexStringToColor(fighter(a.id).color).color;this.fx.lineStyle(5,col,.8);this.fx.strokeCircle(a.x,ground+a.y-95,36+age%28*3);}
    if(a.action==='special'){const col=Phaser.Display.Color.HexStringToColor(fighter(a.id).color).color;this.fx.lineStyle(4,col,.7);if(activeMove(a).kind==='burst'&&age>=18&&age<35)this.fx.strokeCircle(a.x,ground+a.y-65,80+(age-18)*4);else if(age<18||a.id==='graumacher'&&age<44){this.fx.strokeCircle(a.x+a.face*42,ground+a.y-65,10+age%16);if(a.id==='graumacher'){this.fx.fillStyle(0xcdd3e2,.12+.1*Math.sin(age));this.fx.fillRect(0,FLOOR-14,960,20);}}}
   });
   for(const p of match.projectiles){const c=Phaser.Display.Color.HexStringToColor(p.color).color;for(let glow=3;glow>0;glow--){this.fx.fillStyle(c,.065*glow);this.fx.fillCircle(p.x-p.vx*.025*glow,ground+p.y,p.radius*(1+glow*.38));}this.fx.fillStyle(c,1);this.fx.fillRoundedRect(p.x-p.radius,ground+p.y-p.radius,p.radius*2,p.radius*2,5);this.fx.fillStyle(0xffffff,.95);this.fx.fillRect(p.x-4,ground+p.y-7,8,14);this.fx.lineStyle(2,0xffffff,.8);this.fx.strokeCircle(p.x,ground+p.y,p.radius*.8);}
   if(config.training&&boxes){for(const a of match.actors){const body=hurtbox(a),hit=activeHitbox(a);this.fx.lineStyle(2,0x6cfcc8,.95);this.fx.strokeRect(body.x,ground+body.y,body.w,body.h);if(hit){this.fx.lineStyle(2,0xff705c,.95);this.fx.strokeRect(hit.x,ground+hit.y,hit.w,hit.h)}}for(const p of match.projectiles){this.fx.lineStyle(2,0xff705c,.95);this.fx.strokeRect(p.x-p.radius,ground+p.y-p.radius,p.radius*2,p.radius*2)}}
   if(match.phase==='intro'){const text=config.boss&&match.round===1&&match.phaseTicks>85?bossLabel(config.boss)+'\n'+fighter(config.p2).name.toUpperCase():match.phaseTicks>36?`RUNDE ${match.round}`:'FIGHT!';this.banner.setText(text).setFontSize(text.length>25?29:45);}
   else if(match.phase==='roundover')this.banner.setText(match.roundWinner===null?'UNENTSCHIEDEN':match.phaseTicks<78?fighter(match.actors[match.roundWinner].id).short.toUpperCase()+' GEWINNT':match.actors[1-match.roundWinner].hp<=0?'K.O.!':'ZEIT ABGELAUFEN').setFontSize(match.phaseTicks<78?40:56);
   else if(match.phase==='fight'&&match.time>65*60-24)this.banner.setText('FIGHT!').setFontSize(54);
   else this.banner.setText('');
  }
  burst(x:number,y:number,color:number){for(let j=0;j<12;j++){const angle=j*Math.PI/6,rect=this.add.rectangle(x,y,6+j%3*2,4,color).setDepth(25);this.tweens.add({targets:rect,x:x+Math.cos(angle)*(35+j%4*12),y:y+Math.sin(angle)*45,alpha:0,duration:220,onComplete:()=>rect.destroy()});}}
  callout(label:string,index:number){const text=this.add.text(index?725:235,245,label.toUpperCase(),{fontFamily:'Pixelify Sans',fontSize:'19px',fontStyle:'bold',color:fighter(match.actors[index].id).color,stroke:'#121329',strokeThickness:6}).setOrigin(.5).setDepth(25);this.tweens.add({targets:text,y:220,alpha:0,delay:550,duration:250,onComplete:()=>text.destroy()});}
 }
 // The surrounding console scales once as a whole. Phaser must not measure that transformed
 // parent and scale again, otherwise high-resolution/fullscreen windows double the arena size.
 const game=new Phaser.Game({type:Phaser.AUTO,parent,width:960,height:540,backgroundColor:'#12172f',pixelArt:true,roundPixels:true,antialias:false,scene:Arena,audio:{noAudio:true},input:{keyboard:true,gamepad:true},scale:{mode:Phaser.Scale.NONE,autoCenter:Phaser.Scale.NO_CENTER},banner:false});
 return {training:(options)=>{if(options.boxes!==undefined)boxes=options.boxes;if(options.dummy)dummy=options.dummy;if(options.reset)match=createMatch(config.p1,config.p2,19,{parry:config.parry,turbo:config.turbo,partners:config.partners,stageId:config.stationId,training:true});},pause:(p)=>{paused=p;config.network?.pause(p);accumulator=0;controls.clear();audio.pause(p);},touch:(key,value)=>controls.touch[key]=value,destroy:()=>{config.network?.destroy();controls.destroy();game.destroy(true);}};
}

