'use client';
import {useEffect,useRef,useState} from 'react';
import {createAnimatedTitle} from './title-motion';

type Props={onPower:()=>void;hasSave:boolean;full:boolean;suspended:boolean;onArcade:(pad:number|null)=>void;onVersus:(pad:number|null)=>void;onCpu:(pad:number|null)=>void;onOnline:(pad:number|null)=>void;onTraining:(pad:number|null)=>void;onContinue:()=>void;onFull:()=>void;onHelp:()=>void;onAudio:()=>void;onCredits:()=>void;onRules:()=>void;onSound:()=>void};
type Page='attract'|'menu'|'duel'|'options';
export function TitleScreen(props:Props){const [page,setPage]=useState<Page>('attract'),[selected,setSelected]=useState(0),[ready,setReady]=useState(false);const canvas=useRef<HTMLCanvasElement>(null),state=useRef({page,selected,props,ready});state.current={page,selected,props,ready};
 const entries:{label:string;run:(pad:number|null)=>void}[]=page==='attract'?[{label:'START DRÜCKEN',run:()=>{props.onPower();setPage('menu');setSelected(0)}}]:page==='menu'?[...(props.hasSave?[{label:'FORTSETZEN',run:props.onContinue}]:[]),{label:'ARCADE',run:props.onArcade},{label:'VERSUS',run:()=>{setPage('duel');setSelected(0)}},{label:'ONLINE',run:props.onOnline},{label:'TRAINING',run:props.onTraining},{label:'OPTIONEN',run:()=>{setPage('options');setSelected(0)}}]:page==='duel'?[{label:'GEGEN COMPUTER',run:props.onCpu},{label:'GEGEN MENSCHEN',run:props.onVersus},{label:'ZURÜCK',run:()=>{setPage('menu');setSelected(0)}}]:[{label:'SPIELEINSTELLUNGEN',run:props.onRules},{label:props.full?'FENSTERMODUS':'VOLLBILD',run:props.onFull},{label:'STEUERUNG',run:props.onHelp},{label:'SOUND',run:props.onAudio},{label:'CREDITS',run:props.onCredits},{label:'ZURÜCK',run:()=>{setPage('menu');setSelected(0)}}];
 const menu=useRef(entries);menu.current=entries;
 const baseline=(i:number,count:number)=>page==='attract'?290:244+(6-count)*7+i*16;
 const activate=(index:number,pad:number|null=null)=>{if(props.suspended||!ready)return;props.onSound();entries[index]?.run(pad)};
 const activateRef=useRef(activate);activateRef.current=activate;
 useEffect(()=>{const el=canvas.current!,ctx=el.getContext('2d')!;let active=true,raf=0,loaded=false,fontReady=false,padHeld=false,backHeld=false,direction=0,nextDirection=0;const animated=createAnimatedTitle();let animationReady=false,elapsed=0,lastTime=0;void animated.ready.then(()=>{animationReady=true;if(active&&fontReady)setReady(true)});const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');const art=new Image();art.src='/assets/title-screen-snes.png';art.onload=()=>{loaded=true;if(active&&fontReady)setReady(true)};art.onerror=()=>{if(active&&fontReady)setReady(true)};void document.fonts.load('12px "Press Start"').then(()=>{fontReady=true;if(active&&(loaded||animationReady||art.complete))setReady(true)});
 const move=(delta:number)=>{setSelected(value=>(value+delta+menu.current.length)%menu.current.length);state.current.props.onSound()};
 const back=()=>{if((state.current.page==='options'||state.current.page==='duel')){setPage('menu');setSelected(0)}else if(state.current.page==='menu')setPage('attract')};
 const onKey=(e:KeyboardEvent)=>{if(state.current.props.suspended||!state.current.ready)return;if(['ArrowUp','ArrowDown','KeyW','KeyS','Enter','Space','Escape'].includes(e.code)){e.preventDefault();if(e.repeat)return;if(['ArrowUp','KeyW'].includes(e.code))move(-1);else if(['ArrowDown','KeyS'].includes(e.code))move(1);else if(e.code==='Escape')back();else activateRef.current(state.current.selected)}};
 window.addEventListener('keydown',onKey);
 const text=(label:string,x:number,y:number,size:number,color:string,align:CanvasTextAlign='center')=>{ctx.font=`${size}px "Press Start",monospace`;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.fillStyle='#08112b';ctx.fillText(label,x+1,y+2);ctx.fillStyle=color;ctx.fillText(label,x,y)};
 const draw=(time:number)=>{if(!active)return;raf=requestAnimationFrame(draw);const current=state.current;ctx.imageSmoothingEnabled=false;ctx.fillStyle='#060c27';ctx.fillRect(0,0,640,360);if(!current.props.suspended&&!document.hidden&&animationReady)elapsed+=Math.min((time-(lastTime||time))/1000,.05);lastTime=time;if(!animationReady||!animated.draw(ctx,elapsed,motionPreference.matches)){if(loaded)ctx.drawImage(art,0,0,640,360)}const count=menu.current.length,start=244+(6-count)*7;
 if(current.page==='attract'){const blink=current.props.suspended||motionPreference.matches||Math.floor(time/680)%3!==2;if(blink)text('START DRÜCKEN',320,290,12,'#ffedb4');text('ENTER  /  A',320,312,6,'#a8bdd8');}
 else {menu.current.forEach((item,i)=>{const y=start+i*16,chosen=i===current.selected;const color=chosen?'#ffe292':'#d5deef';text(item.label,320,y,9,color);if(chosen){ctx.fillStyle='#ffe292';const x=320-ctx.measureText(item.label).width/2-15;ctx.fillRect(x,y-8,3,9);ctx.fillRect(x+3,y-6,3,5);ctx.fillRect(x+6,y-4,2,1)}});text('↑ ↓ WÄHLEN    A BESTÄTIGEN    B ZURÜCK',320,341,5,'#9caccc');}
 if(current.props.suspended)return;const pad=Array.from(navigator.getGamepads?.()??[]).find(p=>p?.connected),b=(n:number)=>pad?.buttons[n]?.pressed??false;const confirm=b(0)||b(9),cancel=b(1),dy=(b(13)||(pad?.axes[1]??0)>.5)?1:(b(12)||(pad?.axes[1]??0)<-.5)?-1:0;if(confirm&&!padHeld)activateRef.current(current.selected,pad?.index??null);if(cancel&&!backHeld)back();if(dy&&(dy!==direction||time>nextDirection)){move(dy);nextDirection=time+(dy!==direction?320:150)}direction=dy;padHeld=confirm;backHeld=cancel;
 };raf=requestAnimationFrame(draw);return()=>{active=false;cancelAnimationFrame(raf);window.removeEventListener('keydown',onKey)};
 },[]);
 return <section className={`snes-title-screen title-${page}`} aria-label="Super Mack Fighters Turbo – Titelbild"><h1 className="sr-only">Super Mack Fighters Turbo</h1><canvas ref={canvas} width="640" height="360" aria-hidden="true"/><div className="title-interactions" role="group" aria-label={page==='attract'?'Spiel starten':page==='menu'?'Hauptmenü':page==='duel'?'Freier Kampf':'Optionen'}>{entries.map((entry,i)=><button key={entry.label} disabled={!ready} aria-label={entry.label} aria-pressed={page!=='attract'?i===selected:undefined} className="title-hit" style={{top:baseline(i,entries.length)*2-25,left:390,width:500,height:34}} onPointerMove={()=>setSelected(i)} onFocus={()=>setSelected(i)} onClick={()=>activate(i)}>{entry.label}</button>)}</div></section>;
}
